### ISSUE TITLE
Remove stale branch 6815f07cd23e

### ISSUE THREAD

**Issue by Puddlestomper** [TheCherno/Hazel#101]
Branch [6815f07cd23e](https://github.com/TheCherno/Hazel/tree/6815f07cd23e) is a Stale Branch. It is 58 commits behind master as of writing this issue. This branch should either be removed or converted into a useful branch (e.g. for pull requests as referenced in issue #54).

**Comment by CleverSource** [comment]
This branch was made to show a diff, the branch can be removed as it doesn't matter.

**Comment by CleverSource** [comment]
Furthermore, I do agree there should be a branch specifically for community suggestions as it would be confusing if a new feature from the community was randomly in master branch and was never shown in the series.

I do think bug fixes and optimizations should be put into master such as PRs like: #98, #83, #93, #92, #72, and #65. Just to name a few.

In my opinion, what should *not* be added into master branch are major features such as PR #91 (sorry Lovely! 😛) as it wouldn't make sense that a big feature such as that was randomly in the main branch for the series.

**Comment by LovelySanta** [comment]
I totaly agree, up till now, only bugfixes are pushed into master. Features such as #82 or #92 do at least need to be mensioned in a video, or even fully implemented by cherno himself.

**Comment by CleverSource** [comment]
Cherno could possibly dedicate the video to that person who made the PR but implement the feature in his own way in a video? I think that would be a decent idea.

**Comment by LovelySanta** [comment]
Requesting a review from @TheCherno to remove Branch [6815f07cd23e](https://github.com/TheCherno/Hazel/tree/6815f07cd23e) for resolving this issue.

**Comment by LovelySanta** [comment]
> I feel like this branch became more of a suggestion though. This branch should possibly stay open even after Cherno deletes the stale branch as OP does recommend Cherno makes a pull request branch.

I rather want to close an unused branch and create a new issue for a PR branch instead. It was already suggested multiple times, for example to pull homework changes, or community additions

**Comment by LovelySanta** [comment]
Branch deleted 👍
