### ISSUE TITLE
Automatically adding sub modules

### ISSUE THREAD

**Issue by Witty13** [TheCherno/Hazel#104]
Is there a way to connect the sub modules automatically when you first download a copy of Hazel? It is not that hard to add the sub modules through git before using the bat file but I was wondering if there was a way to do this automatically, so that we do not have to go and find each sub module on git hub and then manual add each one. It could become an issue if Hazel uses a slightly different version of the sub modules than the one the the person connects and it would be a big help for those of us who are still fairly new to coding and using git. Thanks.

**Comment by LovelySanta** [comment]
You have 2 options:
1. You can clone Hazel with setting an extra flag:
```git
git clone --recurse https://github.com/TheCherno/Hazel.git
```
2. Change your global settings to **always** (as in, for all github projects) pull the submodules in:
```git
git config --global submodule.recurse true
```
