### ISSUE TITLE
Confusion about Adding VertexBuffers to a VertexArray.

### ISSUE THREAD

**Issue by cheako** [TheCherno/Hazel#117]
For a good while I was thinking that the call to Add a VertexBuffer was meant to push a new buffer onto an Array of Buffers.  The more I though about it the more I realized that the whole idea was madness.

Edit: <ignore>and now figured out that VertexArray refers to an Array of Vertices in a single Buffer.</ignore>

**Comment by cheako** [comment]
https://github.com/TheCherno/Hazel/blob/30b5c242986c67ab20709980f88ca115e65e1261/Hazel/src/Platform/OpenGL/OpenGLVertexArray.h#L24

From what I can tell this is some oGL interface.  What I can't tell is where the VertexBuffer to use is selected or what happens if a draw call is asked to render vertices with different layouts.

For reference this is where I'm tripped up:
https://gitlab.com/cheako/hazel-rs/blob/255cf6ef9fbbc350767d68acd6cec1d5e7cb9026/examples/sandbox.rs#L122

I don't think Vulkan can implement this interface?

**Comment by LovelySanta** [comment]
It is not madness, OpenGL allows to push multiple vertexbuffers (with a single index buffer). Here all pushed vertexbuffers are concatenated into one big buffer.

One example: For our checkerboard, we have a layout of 3 floats for the position + 2 floats for the texture positions. One could split these up and have 2 vertexbuffers: 1 with 3 floats for the position and 2nd one with 2 floats for the texture positions. You only have to make sure the indices are matching (which should be for obvious reasons). Ofcourse you will have to push them in the correct order as well, first the vertex positions, and then the texture coordinates.

For future questions, I suggest you ask them on our [discord](https://discord.gg/K2eSyQA).
