### ISSUE TITLE
LayerStack::PopLayer does not delete the Layer object

### ISSUE THREAD

**Issue by TsarpDev** [TheCherno/Hazel#118]
As long as m_Layers is a std::vector<Layer*> and a std::vector<std::unique_ptr<Layer>>,  calling erase() in LayerStack::PopLayer will set the pointer to null and not delete the object. Do I miss something?

**Comment by WhoseTheNerd** [comment]
There are times you want to reinsert layers. Reallocation can be sometimes very time consuming

**Comment by LovelySanta** [comment]
Or we could pass a boolean to the pop function (with default value)? So you can tell if it has to delete it or not?

**Comment by Puddlestomper** [comment]
Did Cherno mention whether he wants the `LayerStack` to have ownership of Layers? Seeing as we delete all the layers in the LayerStack's destructor I think LayerStack does take ownership of the layers.

> Or we could pass a boolean to the pop function (with default value)? So you can tell if it has to delete it or not?

I like the idea of passing a boolean on whether it should delete it. The default should probably be to delete. The application already has the pointer to the layer just by calling the method so if the application specifies to not delete then we expect it to take ownership of the layer.

We should probably start documenting these things (in the wiki maybe?), but that's another issue.

**Comment by LovelySanta** [comment]
> Did Cherno mention whether he wants the `LayerStack` to have ownership of Layers? Seeing as we delete all the layers in the LayerStack's destructor I think LayerStack does take ownership of the layers.
> 
> > Or we could pass a boolean to the pop function (with default value)? So you can tell if it has to delete it or not?
> 
> I like the idea of passing a boolean on whether it should delete it. The default should probably be to delete. The application already has the pointer to the layer just by calling the method so if the application specifies to not delete then we expect it to take ownership of the layer.
> 
> We should probably start documenting these things (in the wiki maybe?), but that's another issue.

Pop layer could return a reference to the layer if the layer isn't deleted, returning a null when it is deleted maybe? To transfer ownership back? I think these things should be documented, but cherno didn't want to open up the wiki yet...

**Comment by Puddlestomper** [comment]
My suggested solution was going to be returning the pointer to the popped layer, but seeing as the application already has to provide the pointer to the layer as a function parameter in the first place it seem rather pointless (pun not intended).

We should probably make a separate issue about documentation for Hazel.

**Comment by LovelySanta** [comment]
> My suggested solution was going to be returning the pointer to the popped layer, but seeing as the application already has to provide the pointer to the layer as a function parameter in the first place it seem rather pointless (pun not intended).

You require a reference to the layer to pop it, so the caller of popping the layer can delete this as well... So I think we should stick with not deleting the layer when poping and let the caller delete it (or not, so it can be pushed again).

So with this reasoning, I think this can be closed as it is not realy a bug in the LayerStack?

> We should probably make a separate issue about documentation for Hazel.

Same response as before: Make a community driven wiki and go from there... I'm hapy to create some github.io page for it and allow anyone to contribute... This should be a seperate PR. But the general answer: cherno didn't open any official wiki/documentation place so far.
