### ISSUE TITLE
Future design criteria for shaders with Vulkan UBO support?

### ISSUE THREAD

**Issue by cheako** [TheCherno/Hazel#119]
I'm attempting to implement Hazel on Vulkan and Rust.  I've come to an issue with the current shaders, Vulkan only supports Uniform Buffer Objects.  Making the transition can happen in a number of ways and I'm trying to end up with what Hazel would have for it's shaders that would support Vulkan....  or if I need to do something special to compile the shaders?
https://gitlab.com/cheako/hazel-rs/commit/d1a5c236f3317eb98a4cc3696f61ffcc0e4d347c   Here is my commit taking a stab at using the same data and shaders as the current public Hazel, it doesn't run because the PipelineLayout doesn't have the UBOs.  While adding them I decided I couldn't just do what I did for my Vulkan example application: https://gitlab.com/cheako/cheako-vulkan/blob/master/0007shared-ubo.diff

**Comment by CleverSource** [comment]
This is the incorrect place to post an issue like this. 

Firstly you're using a different programming language and secondly it is a personal issue. I recommend for further support you ask via the [Cherno Discord](https://discord.gg/k9Hv5p6).

This issue can be closed.

**Comment by cheako** [comment]
@CleverSource Thanks for your reply!  I asked on the discord server and got no response...  As discord posts are eventually buried it's important to put this discussion somewhere where it won't be lost.

I'm asking about this project, see subject.

**Comment by CleverSource** [comment]
But this is for issues relating to the project itself, your asking a question related to a project done by you where you convert this into Rust and port it to Vulkan.

**Comment by cheako** [comment]
No, again I refer you to the subject/title.  It's clearly talking about the FUTURE DESIGN of this(by association, the one you are bringing up) project.

The reference to an EXAMPLE, providing a simple way to experiment with this idea.

**Comment by LovelySanta** [comment]
We're still in a state where the API is a 'get it up and working', and go from there. Cherno did mension that the API could have some API specific functions. You can check what API we're using with `Renderer::GetAPI()`.

This way you can have a generic implementation with the 'basic' API and have a specific (more optimised) implementation for example for Vulkan only.

I hope this answers your question? It is too early to think about other renderers and render specific code as we're still working on the OpenGL implementation and get stuff working.

**Comment by cheako** [comment]
@LovelySanta Thanks for the feedback, I think it's great to have these points documented as I was thinking along those lines.  I've never written multi-api shaders and I didn't want to just guess, without asking.

I don't think this issue and the others representing Vulkan TODO should pollute the issues page.  Can I write a wiki article as a place for these items to live?  I think I need someone to create the page and give me write permissions.  As I'm working on a project affected by these I'd be happy to keep the information up to date.

Thanks.

**Comment by LovelySanta** [comment]
> @LovelySanta Thanks for the feedback, I think it's great to have these points documented as I was thinking along those lines. I've never written multi-api shaders and I didn't want to just guess, without asking.

The reason we don't have it documented yet is because the current API won't make the final product, I can tell you that with a 99% certainty. As long as we don't have some API that can more or less be representative (as in, we are creating stuff to get stuff up and running atm), cherno did not open the wiki or any documentation pages yet.

> I don't think this issue and the others representing Vulkan TODO should pollute the issues page. Can I write a wiki article as a place for these items to live? I think I need someone to create the page and give me write permissions. As I'm working on a project affected by these I'd be happy to keep the information up to date.

As this is not an issue, I'll close this. Thanks for wanting to contribute, but you're a bit too early to think about documentation.

**Comment by cheako** [comment]
The solution I came up with for this is applicable to the cpp/opengl version.  Currently the client uses uniform names that are hard coded in Hazel.  I wanted to avoid that.  I'm still developing my solution, but I thought I'd share my experience thus far.  The solution is to use reflection, with SPIRV Cross.

In my solution the client writes shaders using whatever names they want and then in cpp values are assigned using the names from the shader.  So for example the draw call takes in the names of the two mat4 for the camera.  The change from uniforms to uniform buffer objects meant that a struct must be used, though the names, sizes, and offsets of members are queryable.  So the client passes in a hashmap of names and currently the raw data and hazel-rs does all the lifting.

In Hazel shaderc would be used to compile the shaders to SPIR-V and then SPIRV Cross would reflect and compile the shaders for the current API.

I would help implement this for Hazel, but I'm trying to live without cpp for the time being.  Though I can answer questions and help identify problems.
