### ISSUE TITLE
[Question]Client script compilation

### ISSUE THREAD

**Issue by rikseth** [TheCherno/Hazel#141]
How do game engines like Unreal Engine compile client written cpp code? I have seen while working on unreal engine that when I press the play button it compiles the CPP code that I have written. How does it does so and then links the code to the game?

**Comment by SeppahBaws** [comment]
So from the little that I know about Unreal, it does this using their "Unreal Header Tool".

It is responsible for parsing the header files and generating "custom code to implement the various UObject-related features". After that it invokes the c++ compiler to compile these results. [Here's more information.](https://docs.unrealengine.com/en-US/Programming/BuildTools/index.html)

From sniffing around in a project I also found that Unreal Engine compiles your source code into a DLL, which I assume is then imported into the editor and ran when you press play.

**Comment by LovelySanta** [comment]
If you still need more information, I kindly ask you to go to our [discord server](https://discord.gg/K2eSyQA).
