### ISSUE TITLE
FYI: Runtime Library Configuration

### ISSUE THREAD

**Issue by rezss** [TheCherno/Hazel#15]
Hey,
you mentioned in your video [Layers Game Engine series](https://youtu.be/_Kj6BSfM6P4?t=1078) you'd like to know a way how to control the Runtime Library Configuration via Premake.

Premake has to functions for that, the first one (that you already set btw.) is [staticruntime](https://github.com/premake/premake-core/wiki/staticruntime), by turning it on or off you configure either if visual studio should use the Multi-Threaded Static or DLL Runtime.
Second you have [runtime](https://github.com/premake/premake-core/wiki/runtime) that controls either the debug or non debug Runtime, if static or DLL is still determined by staticruntime.

Hope that helps, 
Cheers

**Comment by TheCherno** [comment]
Thank you for letting me know! This has been implemented in the latest video. 😄
