### ISSUE TITLE
Discussion: The future of the project?

### ISSUE THREAD

**Issue by stevefan1999-personal** [TheCherno/Hazel#160]
So this project is lit🔥and from the simplicity of the code structure I felt in love with it, I saw a lot of potentials in it. 

However, I wonder if this is going to evolve as a full-blown engine, or still, step down as an academic source for teaching how game engine works?

In other words, will this be production ready eventually, or will it never be? I think this would be an interesting question to ask.

**Comment by Puddlestomper** [comment]
I believe @TheCherno does want this to be a fully usable and fully featured Game Engine eventually. But at the rate it is going this will probably take at least another year. I think the educational goal comes first, so there is a limit on how fast he can develop this. But he has also mentioned wanting to move to diffs soon which should allow him to cover more changes per video and speed up development.

My plan is to stick with this for the long run. I've learned and I am continuing to learn a lot and as long as that continues I don't really mind that a release is still far off. I'm guessing the first proper release will be when we finish 2D rendering - although Cherno might want to implement many more non-rendering related systems before then.

**Comment by LovelySanta** [comment]
Closing this as answered.
