### ISSUE TITLE
Possible Incorrect Vertex Array Target 

### ISSUE THREAD

**Issue by cxgslegend** [TheCherno/Hazel#164]
I could be completely wrong about this. I am new to OpenGL, but every tutorial I see uses the target of GL_ELEMENT_ARRAY_BUFFER when making an index buffer. In OpenGLBuffer.cpp, we are using GL_ARRAY_BUFFER for both the index and vertex buffer.

**Comment by CleverSource** [comment]
This pull request can give clarification on why this is done; https://github.com/TheCherno/Hazel/pull/107.

**Comment by cxgslegend** [comment]
Hmm, I guess I understand why it is working now. I see in the docs it says "When a buffer object is bound to a target, the previous binding for that target is automatically broken.". 

So I suppose this means that we first bind it to GL_ARRAY_BUFFER, then when we go to actually use it, we change it via the OpenGLIndexBuffer::Bind() to the target of GL_ELEMENT_ARRAY_BUFFER. Which would break the previous binding to GL_ARRAY_BUFFER. 

However, I am still confused about the point of it. For example in Javascript, I could do the following. 
var mystring = false; 
mystring = "Hello World";
console.log(mystring);

I guess that works, sure. But why? If you intended it to be a string the entire time, why set it to a boolean? 

I guess what I am asking is, what is the benefit? If we bind to GL_ARRAY_BUFFER is there something that we can do that we couldn't with GL_ELEMENT_ARRAY_BUFFER? Is he just doing it so he only has to remember one target name? I'm not against using it, I just want to wrap my head around why its a thing.

**Comment by LovelySanta** [comment]
> I guess what I am asking is, what is the benefit? If we bind to GL_ARRAY_BUFFER is there something that we can do that we couldn't with GL_ELEMENT_ARRAY_BUFFER? Is he just doing it so he only has to remember one target name? I'm not against using it, I just want to wrap my head around why its a thing.

`GL_ARRAY_BUFFER` is just a generic buffer, it can be used for anything, and when we bind it to put data in it, it doesn't matter what kind of buffer we use, bytes are bytes, what they represent is not important at that stage.

If we bind a `GL_ELEMENT_ARRAY_BUFFER`, we know it is an indexbuffer. However, OpenGL *should* give an error if we try to bind an index buffer before having any vertex buffers. The official procedure is to create a vertex array, and then bind the vertex buffers and indexbuffer(s) for those array buffers. This is rather purely for historical reasons of OpenGL itself.

However, as mensioned in https://github.com/TheCherno/Hazel/pull/107#issuecomment-525137043, it could however (on old compilers) throw an error if we try to bind an indexbuffer without having a vertex array. The way we do this now (with just a generic buffer), this is not an issue.

If you still have questions, I would encourage you to read my inital post https://github.com/TheCherno/Hazel/pull/107#issuecomment-524937929 and if you have any more questions, feel free to ask (preferebly on [https://discord.gg/K2eSyQA](our discord server), or here if you really think this is a bug...
