### ISSUE TITLE
[Question]std::async

### ISSUE THREAD

**Issue by OdysseyCreations** [TheCherno/Hazel#167]
I have seen in the CPP videos about ```std::async()```. I have tried creating them but the program crashes at ```glCreateProgram() ``` or ```glCreateTexture() ``` & sometimes at ```glCreateProgram() ```. Googling out I found I need multiple contexts. Thus, in order to load meshes or textures asynchronously, we need multiple contexts (in glfw). But I don't know how is it done. 

So my greatest question since then has been,  HOW DID HE LOADED THE MODELS ___ASYNCHRONOUSLY___?

Did he created multiple contexts or did it in some other method?

**Comment by CleverSource** [comment]
Seeing as this question is related to the C++ series and not the game engine series, I recommend you head to the [Discord](https://discord.gg/zcpBe3f). There are multiple people that can answer this question on there! :)

**Comment by LovelySanta** [comment]
By default, you can only make GL context related calls from the main thread (the one that the context is located on). If you want to create an async task, you can, but you have to create a 2nd GL context that is set to share resources with the main context, or you can let the thread do the hard work, and the (final) context call(s) on the main thread exclusively...

As already mensioned, head to the [Discord](https://discord.gg/zcpBe3f) if you want to have a more in depth answer and/or help with implementation details.
