### ISSUE TITLE
__FUNCSIG__ is not defined on all target platforms.

### ISSUE THREAD

**Issue by GabeRundlett** [TheCherno/Hazel#173]
On both GCC and Clang, `__FUNCSIG__` is not defined. Inside Instrumentor.h, there should be a macro defining `__FUNCSIG__` as `__PRETTY_FUNCTION__` which I've found to be exclusive to *Unix targeted compilers (GCC, Clang, ARM GCC, Arduino's compilers etc.).

since `__FUNCSIG__` isn't defined on all the platforms that `__PRETTY_FUNCTION__` is, the following would fix the issue on all Unix targeted compilers

```cpp
#ifdef __FUNCSIG__
#define __FUNCSIG__ __PRETTY_FUNCTION__
#endif
```

proof it compiles on all target platforms compilers:
https://godbolt.org/z/wtudtn

**Comment by CleverSource** [comment]
You should make a pull request on this.

**Comment by GabeRundlett** [comment]
> You should make a pull request on this. Why would `__FUNCSIG__` be defined as `__PRETTY_FUNCTION__`, seems smarter to just use `__PRETTY_FUNCTION__` instead..?

I submitted a pull request, however, __PRETTY_FUNCTION__ is not defined (at least for me on both my windows machine as well as compiler explorer *linked in the original post*) in MSVC. This way on windows, the `#ifdef` is skipped, and on GCC and Clang `__FUNC_SIG__` is defined as `__PRETTY_FUNCTION__` when `__FUNC_SIG__` is used in the macro in Instrumentor.h.

**Comment by ReDucTor** [comment]
Moving towards C++20 this should hopefully start being replaced with [std::source_location](https://en.cppreference.com/w/cpp/utility/source_location)

**Comment by pmann84** [comment]
It's worth mentioning std::source_location behaves differently on different compilers, so it may not give the desired output on Windows (this is using the latest VS - 16.10).
