### ISSUE TITLE
HZ_ENABLE_ASSERTS never enabled

### ISSUE THREAD

**Issue by LovelySanta** [TheCherno/Hazel#18]
Hello,

In  the core you define the asserts:
https://github.com/TheCherno/Hazel/blob/c65520c96289ab62ecd37995108063ce4019d4e9/Hazel/src/Hazel/Core.h#L13-L19
You never added those to the premake5.lua file, resulting in never asserting the statements in any mode (Debug/Release/Dist).

Kind regards
lovely_santa

**Comment by Ryngetsu** [comment]
I think instead of defining those in the premake file, you should put another layer with HZ_DEBUG or HZ_RELEASE like:

`
#ifdef HZ_DEBUG
    #define HZ_ENABLE_ASSERTS
`

in the Core.h file

**Comment by LovelySanta** [comment]
I think it is indeed beter to define those in the core.h file indeed.

I'll leave this open for @TheCherno if he didn't realise this yet.
If i find an update on this in his video's, then I'll close this myself (if not yet closed by then).

**Comment by SeppahBaws** [comment]
Hey @LovelySanta I saw that this issue was still open.
TheCherno updated this in his latest video on the channel. 🙂
