### ISSUE TITLE
Indexbuffer is using wrong bufferdata type

### ISSUE THREAD

**Issue by LipkeGu** [TheCherno/Hazel#184]
I noticed that the Indexbuffer is using ```GL_ARRAY_BUFFER``` instead of ```GL_ELEMENT_ARRAY_BUFFER``` at ```glBindBuffer(GL_ARRAY_BUFFER, m_RendererID);```

**Comment by ReDucTor** [comment]
This isn't a bug see #95, this keeps coming up should add a comment to the code.

**Comment by LipkeGu** [comment]
OK, then it should be hold a reference to this Kronowiki that it is for 4.6 then on 4.3 it doesnt work like here.

**Comment by LovelySanta** [comment]
We use 4.5 anyway, and the wiki just states that it is (currently) in 4.6, but it also works in 4.5
