### ISSUE TITLE
Instrumentator better function name

### ISSUE THREAD

**Issue by LovelySanta** [TheCherno/Hazel#191]
#### Describe the bug
A followup on https://github.com/TheCherno/Hazel/pull/185#issuecomment-573086649: There is quite a significant overhead by the cleanup of the function name of the instrumentor as mensioned in https://github.com/TheCherno/Hazel/pull/185#issuecomment-569551143.
https://github.com/TheCherno/Hazel/blob/0716731c8e274f2e3d83aefef2222fe189a33728/Hazel/src/Hazel/Debug/Instrumentor.h#L75-L76

As this is already (partialy) resolved, there is still some cleanup to do, as with the different formats of the pretty printing, the std:replace is in some cases unneeded, and in other cases not enough, for example using the msvc compiler, we could still remove the unneeded __cdecl in every function name.

#### To Reproduce
Load a result in [chrome tracing](chrome://tracing/) and check out the function names.

#### Expected behavior
The expected behavior is to have a more uniform function name across (all) compilers.
A possible solution could be to create a static function that returns the correct function name? This function we could differ for each (supported) compiler as we already have the different pretty functions in a macro. This function could even be exposed to other parts of the (future) debugging section of the engine?

**Comment by HerrDingenz** [comment]
replace
        #elif defined(__FUNCSIG__)

with
        #elif defined(_MSC_BUILD)

done ;)

**Comment by HerrDingenz** [comment]
```
//		#elif defined(__FUNCSIG__)
//			#define CL_FUNC_SIG __FUNCSIG__
		#elif defined(_MSC_BUILD)
			#define CL_FUNC_SIG __FUNCTION__

```

works nice with MSVC

**Comment by HerrDingenz** [comment]
remove:

`	#elif defined(__FUNCSIG__)
		#define HZ_FUNC_SIG __FUNCSIG__`

and change

`	#elif (defined(__INTEL_COMPILER) && (__INTEL_COMPILER >= 600)) || (defined(__IBMCPP__) && (__IBMCPP__ >= 500)`

to

`	#elif (defined(__INTEL_COMPILER) && (__INTEL_COMPILER >= 600)) || (defined(__IBMCPP__) && (__IBMCPP__ >= 500)) || defined (_MSC_BUILD))`

**Comment by HerrDingenz** [comment]
we could add a version check to the _MSC_BUILD inspecting _MSC_VER - but who cares?

you can check it out here: https://docs.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=vs-2019
