### ISSUE TITLE
Not hitting break points in Hazel code

### ISSUE THREAD

**Issue by nhoughto5** [TheCherno/Hazel#20]
Visual studio is not able to hit break points set in code in the Hazel project. It can hit breakpoints in the Sandbox app but not in the Engine. 

This seems to be because the generated PDB file is not accessible to the running executable (Sandbox.exe) so it can not load the debugging symbols.

The simple solution is to add an additional post build command step to copy the file over. Something like:

 `("{COPY} ../bin/" .. outputdir .. "/Hazel/Hazel.pdb" .. " ../bin/" .. outputdir .. "/%{prj.name}")`

to the premake5.lua file. 

I would make a PR however in the repo's current state it will probably have the same issue as pointed out [here](https://github.com/TheCherno/Hazel/issues/9). Both this new post command step and the original DLL copy should be moved to the Sandbox project section of the lua file. Because of this I'll just leave it as a suggestion for a future fix.

**Comment by Jujudo** [comment]
Hm, that works for me 🤔

**Comment by Gaztin** [comment]
Closing since this has been resolved.
