### ISSUE TITLE
[Question] Texture???

### ISSUE THREAD

**Issue by OdysseyCreations** [TheCherno/Hazel#205]
While reading https://blogs.unity3d.com/2018/10/08/optimizing-loading-performance-understanding-the-async-upload-pipeline/ I have found that during build unity puts all the textures to an optimized binary file.
Now I am developing my own engine (heavily inspired by yours). There I am working on Texture loading. I already have Asynchronous Texture loading which reduced the loading time down to 50%.
But every time the texture is load stb_image or FreeImage does some post processing and pre processing this increases the loading time a lot in case of big textures like 8k Textures. So I was thinking how can I write the texture to a binary format so that once loaded from the second time it loads from the binary and doesn't take much time?
Now, honestly I am stuck here since I have google but didn't found any answer. My only question is how do they do it? Also, I would like to know how will you implement it to your own engine?

**Comment by Puddlestomper** [comment]
Please keep all questions regarding help with personal projects to [the discord](http://thecherno.com/discord).

**Comment by LovelySanta** [comment]
To be fair, I really think you'll get a faster and more accurate response if you ask it on the discord, for which reasons I'll close this issue.

On another note, @Puddlestomper, should we maybe state this explicitly in the [contributing guidelines](https://github.com/TheCherno/Hazel/blob/master/.github/CONTRIBUTING.md) under the [Reporting Bugs](https://github.com/TheCherno/Hazel/blob/master/.github/CONTRIBUTING.md#reporting-bugs) section or the general introduction (first paragraph)?
