### ISSUE TITLE
Saving Settings and Message Boxes

### ISSUE THREAD

**Issue by CodeEasyYT** [TheCherno/Hazel#208]
#### Is your feature request related to a problem? Please describe
My feature is just a idea.

#### Describe the solution you'd like
What about creating a settings/save system to save some datas. And also can you add message boxes? It could be good.

**Comment by LovelySanta** [comment]
> What about creating a settings/save system to save some datas.

Do you mean something like a todo list? There are plenty of mods similar to that out there...

> And also can you add message boxes?

Like between players? You can use the similar mods like a todo list for that as well..
