### ISSUE TITLE
Linkage problem in vs2019

### ISSUE THREAD

**Issue by acamposruiz** [TheCherno/Hazel#221]
Hi everyone!
First thank you for this amazing project!
I´m very new to Cpp and I´m getting problems with the premake5.lua 
After setting everything up and try to generate solution by premake5 for visual studio 2019 I am getting this error:
```1>------ Build started: Project: Sandbox, Configuration: Debug x64 ------
1>LINK : fatal error LNK1104: cannot open file 'C:\Dev\TheCherno\bin\Debug-windows-x86_64\Hazel\Hazel.lib'
1>Done building project "Sandbox.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```
***This is my project tree:***
```
C:.
|   .gitmodules
|   GenerateProjects.bat
|   premake5.lua
|
+---Hazel
|   +---Debug
|   |   |   Hazel.exe
|   |   |   Hazel.exp
|   |   |   Hazel.ilk
|   |   |   Hazel.lib
|   |   |   Hazel.log
|   |   |   Hazel.pdb
|   |   |   Hazel.vcxproj.FileListAbsolute.txt
|   |   |   Test.obj
|   |   |   vc142.idb
|   |   |   vc142.pdb
|   |   |   vcpkg.applocal.log
|   |   |
|   |   \---Hazel.tlog
|   |           CL.command.1.tlog
|   |           CL.read.1.tlog
|   |           CL.write.1.tlog
|   |           Hazel.lastbuildstate
|   |           Hazel.write.1u.tlog
|   |           link.command.1.tlog
|   |           link.read.1.tlog
|   |           link.write.1.tlog
|   |
|   +---src
|   |   |   Hazel.h
|   |   |
|   |   \---Hazel
|   |           Application.cpp
|   |           Application.h
|   |           Core.h
|   |           EntryPoint.h
|   |           Log.cpp
|   |           Log.h
|   |
|   \---vendor
|       \---spdlog
|           |   .clang-format
|           |   .clang-tidy
|           |   .gitattributes
|           |   .gitignore
|           |   .travis.yml
|           |   appveyor.yml
|           |   CMakeLists.txt
|           |   INSTALL
|           |   LICENSE
|           |   meson.build
|           |   meson_options.txt
|           |   README.md
|           |
|           +---bench
|           |       async_bench.cpp
|           |       bench.cpp
|           |       CMakeLists.txt
|           |       formatter-bench.cpp
|           |       latency.cpp
|           |       meson.build
|           |       utils.h
|           |
|           +---cmake
|           |       ide.cmake
|           |       pch.h.in
|           |       spdlog.pc.in
|           |       spdlogConfig.cmake.in
|           |       spdlogCPack.cmake
|           |       utils.cmake
|           |       version.rc.in
|           |
|           +---example
|           |       CMakeLists.txt
|           |       example.cpp
|           |       meson.build
|           |
|           +---include
|           |   \---spdlog
|           |       |   async.h
|           |       |   async_logger-inl.h
|           |       |   async_logger.h
|           |       |   common-inl.h
|           |       |   common.h
|           |       |   formatter.h
|           |       |   fwd.h
|           |       |   logger-inl.h
|           |       |   logger.h
|           |       |   pattern_formatter-inl.h
|           |       |   pattern_formatter.h
|           |       |   spdlog-inl.h
|           |       |   spdlog.h
|           |       |   tweakme.h
|           |       |   version.h
|           |       |
|           |       +---cfg
|           |       |       argv.h
|           |       |       env.h
|           |       |       helpers-inl.h
|           |       |       helpers.h
|           |       |       log_levels.h
|           |       |
|           |       +---details
|           |       |       backtracer-inl.h
|           |       |       backtracer.h
|           |       |       circular_q.h
|           |       |       console_globals.h
|           |       |       file_helper-inl.h
|           |       |       file_helper.h
|           |       |       fmt_helper.h
|           |       |       log_msg-inl.h
|           |       |       log_msg.h
|           |       |       log_msg_buffer-inl.h
|           |       |       log_msg_buffer.h
|           |       |       mpmc_blocking_q.h
|           |       |       null_mutex.h
|           |       |       os-inl.h
|           |       |       os.h
|           |       |       periodic_worker-inl.h
|           |       |       periodic_worker.h
|           |       |       registry-inl.h
|           |       |       registry.h
|           |       |       synchronous_factory.h
|           |       |       tcp_client-windows.h
|           |       |       tcp_client.h
|           |       |       thread_pool-inl.h
|           |       |       thread_pool.h
|           |       |       windows_include.h
|           |       |
|           |       +---fmt
|           |       |   |   bin_to_hex.h
|           |       |   |   fmt.h
|           |       |   |   ostr.h
|           |       |   |
|           |       |   \---bundled
|           |       |           chrono.h
|           |       |           color.h
|           |       |           compile.h
|           |       |           core.h
|           |       |           format-inl.h
|           |       |           format.h
|           |       |           LICENSE.rst
|           |       |           locale.h
|           |       |           ostream.h
|           |       |           posix.h
|           |       |           printf.h
|           |       |           ranges.h
|           |       |
|           |       \---sinks
|           |               android_sink.h
|           |               ansicolor_sink-inl.h
|           |               ansicolor_sink.h
|           |               base_sink-inl.h
|           |               base_sink.h
|           |               basic_file_sink-inl.h
|           |               basic_file_sink.h
|           |               daily_file_sink.h
|           |               dist_sink.h
|           |               dup_filter_sink.h
|           |               msvc_sink.h
|           |               null_sink.h
|           |               ostream_sink.h
|           |               ringbuffer_sink.h
|           |               rotating_file_sink-inl.h
|           |               rotating_file_sink.h
|           |               sink-inl.h
|           |               sink.h
|           |               stdout_color_sinks-inl.h
|           |               stdout_color_sinks.h
|           |               stdout_sinks-inl.h
|           |               stdout_sinks.h
|           |               syslog_sink.h
|           |               systemd_sink.h
|           |               tcp_sink.h
|           |               wincolor_sink-inl.h
|           |               wincolor_sink.h
|           |               win_eventlog_sink.h
|           |
|           +---logos
|           |       jetbrains-variant-4.svg
|           |
|           +---scripts
|           |       extract_version.py
|           |       format.sh
|           |
|           +---src
|           |       async.cpp
|           |       cfg.cpp
|           |       color_sinks.cpp
|           |       file_sinks.cpp
|           |       fmt.cpp
|           |       spdlog.cpp
|           |       stdout_sinks.cpp
|           |
|           \---tests
|                   catch.hpp
|                   catch.license
|                   CMakeLists.txt
|                   includes.h
|                   main.cpp
|                   meson.build
|                   test_async.cpp
|                   test_backtrace.cpp
|                   test_cfg.cpp
|                   test_create_dir.cpp
|                   test_daily_logger.cpp
|                   test_dup_filter.cpp
|                   test_errors.cpp
|                   test_eventlog.cpp
|                   test_file_helper.cpp
|                   test_file_logging.cpp
|                   test_fmt_helper.cpp
|                   test_macros.cpp
|                   test_misc.cpp
|                   test_mpmc_q.cpp
|                   test_pattern_formatter.cpp
|                   test_registry.cpp
|                   test_sink.h
|                   test_stdout_api.cpp
|                   test_systemd.cpp
|                   utils.cpp
|                   utils.h
|
+---Sandbox
|   \---src
|           SandboxApp.cpp
|
\---vendor
    \---bin
        \---premake
                premake5.exe

```

And this is the content from my ***premake5.lua*** file:
```
workspace "Hazel"
	architecture "x64"

	configurations
	{
		"Debug",
		"Release",
		"Dist"
	}

outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"

project "Hazel"
	location "Hazel"
	kind "SharedLib"
	language "C++"

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

	files
	{
		"%{prj.name}/src/**.h",
		"%{prj.name}/src/**.cpp"
	}

	includedirs
	{
		"%{prj.name}/vendor/spdlog/include"
	}

	filter "system:windows"
		cppdialect "C++17"
		staticruntime "On"
		systemversion "latest"

		defines
		{
			"HZ_PLATFORM_WINDOWS",
			"HZ_BUILD_DLL"
		}

		postbuildcommands
		{
			("{COPY} %{cfg.buildtarget.relpath} ../bin/" .. outputdir .. "/Sandbox")
		}

	filter "configurations:Debug"
		defines "HZ_DEBUG"
		symbols "On"

	filter "configurations:Release"
		defines "HZ_RELEASE"
		optimize "On"

	filter "configurations:Dist"
		defines "HZ_DIST"
		optimize "On"

project "Sandbox"
	location "Sandbox"
	kind "ConsoleApp"
	language "C++"

	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")

	files
	{
		"%{prj.name}/src/**.h",
		"%{prj.name}/src/**.cpp"
	}

	includedirs
	{
		"Hazel/vendor/spdlog/include",
		"Hazel/src"
	}

	links
	{
		"Hazel"
	}

	filter "system:windows"
		cppdialect "C++17"
		staticruntime "On"
		systemversion "latest"

		defines
		{
			"HZ_PLATFORM_WINDOWS"
		}

	filter "configurations:Debug"
		defines "HZ_DEBUG"
		symbols "On"

	filter "configurations:Release"
		defines "HZ_RELEASE"
		optimize "On"

	filter "configurations:Dist"
		defines "HZ_DIST"
		optimize "On"

```
Do anyone in this community knows where could be the problem or how could I approaching it?
Thank you in advance for any comment!

**Comment by LovelySanta** [comment]
If I recall correctly, that's the error when sandbox is not set as startup project:
https://github.com/TheCherno/Hazel/blob/3d5068b9bd665bc0030de4c6bb5b9745a2dd3171/premake5.lua#L3

For future questions, please join [Cherno's discord](https://discord.gg/K2eSyQA) and ask your questions there, you're far more likely to get an answer there.

**Comment by acamposruiz** [comment]
Thank you very much for your response @LovelySanta !
I will join to Cherno's discord in nexts questions as you suggest ;)

**Comment by Aunter1992** [comment]
> Hi everyone!
> First thank you for this amazing project!
> I´m very new to Cpp and I´m getting problems with the premake5.lua
> After setting everything up and try to generate solution by premake5 for visual studio 2019 I am getting this error:
> 
> ```
> 1>LINK : fatal error LNK1104: cannot open file 'C:\Dev\TheCherno\bin\Debug-windows-x86_64\Hazel\Hazel.lib'
> 1>Done building project "Sandbox.vcxproj" -- FAILED.
> ========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
> ```
> 
> _**This is my project tree:**_
> 
> ```
> C:.
> |   .gitmodules
> |   GenerateProjects.bat
> |   premake5.lua
> |
> +---Hazel
> |   +---Debug
> |   |   |   Hazel.exe
> |   |   |   Hazel.exp
> |   |   |   Hazel.ilk
> |   |   |   Hazel.lib
> |   |   |   Hazel.log
> |   |   |   Hazel.pdb
> |   |   |   Hazel.vcxproj.FileListAbsolute.txt
> |   |   |   Test.obj
> |   |   |   vc142.idb
> |   |   |   vc142.pdb
> |   |   |   vcpkg.applocal.log
> |   |   |
> |   |   \---Hazel.tlog
> |   |           CL.command.1.tlog
> |   |           CL.read.1.tlog
> |   |           CL.write.1.tlog
> |   |           Hazel.lastbuildstate
> |   |           Hazel.write.1u.tlog
> |   |           link.command.1.tlog
> |   |           link.read.1.tlog
> |   |           link.write.1.tlog
> |   |
> |   +---src
> |   |   |   Hazel.h
> |   |   |
> |   |   \---Hazel
> |   |           Application.cpp
> |   |           Application.h
> |   |           Core.h
> |   |           EntryPoint.h
> |   |           Log.cpp
> |   |           Log.h
> |   |
> |   \---vendor
> |       \---spdlog
> |           |   .clang-format
> |           |   .clang-tidy
> |           |   .gitattributes
> |           |   .gitignore
> |           |   .travis.yml
> |           |   appveyor.yml
> |           |   CMakeLists.txt
> |           |   INSTALL
> |           |   LICENSE
> |           |   meson.build
> |           |   meson_options.txt
> |           |   README.md
> |           |
> |           +---bench
> |           |       async_bench.cpp
> |           |       bench.cpp
> |           |       CMakeLists.txt
> |           |       formatter-bench.cpp
> |           |       latency.cpp
> |           |       meson.build
> |           |       utils.h
> |           |
> |           +---cmake
> |           |       ide.cmake
> |           |       pch.h.in
> |           |       spdlog.pc.in
> |           |       spdlogConfig.cmake.in
> |           |       spdlogCPack.cmake
> |           |       utils.cmake
> |           |       version.rc.in
> |           |
> |           +---example
> |           |       CMakeLists.txt
> |           |       example.cpp
> |           |       meson.build
> |           |
> |           +---include
> |           |   \---spdlog
> |           |       |   async.h
> |           |       |   async_logger-inl.h
> |           |       |   async_logger.h
> |           |       |   common-inl.h
> |           |       |   common.h
> |           |       |   formatter.h
> |           |       |   fwd.h
> |           |       |   logger-inl.h
> |           |       |   logger.h
> |           |       |   pattern_formatter-inl.h
> |           |       |   pattern_formatter.h
> |           |       |   spdlog-inl.h
> |           |       |   spdlog.h
> |           |       |   tweakme.h
> |           |       |   version.h
> |           |       |
> |           |       +---cfg
> |           |       |       argv.h
> |           |       |       env.h
> |           |       |       helpers-inl.h
> |           |       |       helpers.h
> |           |       |       log_levels.h
> |           |       |
> |           |       +---details
> |           |       |       backtracer-inl.h
> |           |       |       backtracer.h
> |           |       |       circular_q.h
> |           |       |       console_globals.h
> |           |       |       file_helper-inl.h
> |           |       |       file_helper.h
> |           |       |       fmt_helper.h
> |           |       |       log_msg-inl.h
> |           |       |       log_msg.h
> |           |       |       log_msg_buffer-inl.h
> |           |       |       log_msg_buffer.h
> |           |       |       mpmc_blocking_q.h
> |           |       |       null_mutex.h
> |           |       |       os-inl.h
> |           |       |       os.h
> |           |       |       periodic_worker-inl.h
> |           |       |       periodic_worker.h
> |           |       |       registry-inl.h
> |           |       |       registry.h
> |           |       |       synchronous_factory.h
> |           |       |       tcp_client-windows.h
> |           |       |       tcp_client.h
> |           |       |       thread_pool-inl.h
> |           |       |       thread_pool.h
> |           |       |       windows_include.h
> |           |       |
> |           |       +---fmt
> |           |       |   |   bin_to_hex.h
> |           |       |   |   fmt.h
> |           |       |   |   ostr.h
> |           |       |   |
> |           |       |   \---bundled
> |           |       |           chrono.h
> |           |       |           color.h
> |           |       |           compile.h
> |           |       |           core.h
> |           |       |           format-inl.h
> |           |       |           format.h
> |           |       |           LICENSE.rst
> |           |       |           locale.h
> |           |       |           ostream.h
> |           |       |           posix.h
> |           |       |           printf.h
> |           |       |           ranges.h
> |           |       |
> |           |       \---sinks
> |           |               android_sink.h
> |           |               ansicolor_sink-inl.h
> |           |               ansicolor_sink.h
> |           |               base_sink-inl.h
> |           |               base_sink.h
> |           |               basic_file_sink-inl.h
> |           |               basic_file_sink.h
> |           |               daily_file_sink.h
> |           |               dist_sink.h
> |           |               dup_filter_sink.h
> |           |               msvc_sink.h
> |           |               null_sink.h
> |           |               ostream_sink.h
> |           |               ringbuffer_sink.h
> |           |               rotating_file_sink-inl.h
> |           |               rotating_file_sink.h
> |           |               sink-inl.h
> |           |               sink.h
> |           |               stdout_color_sinks-inl.h
> |           |               stdout_color_sinks.h
> |           |               stdout_sinks-inl.h
> |           |               stdout_sinks.h
> |           |               syslog_sink.h
> |           |               systemd_sink.h
> |           |               tcp_sink.h
> |           |               wincolor_sink-inl.h
> |           |               wincolor_sink.h
> |           |               win_eventlog_sink.h
> |           |
> |           +---logos
> |           |       jetbrains-variant-4.svg
> |           |
> |           +---scripts
> |           |       extract_version.py
> |           |       format.sh
> |           |
> |           +---src
> |           |       async.cpp
> |           |       cfg.cpp
> |           |       color_sinks.cpp
> |           |       file_sinks.cpp
> |           |       fmt.cpp
> |           |       spdlog.cpp
> |           |       stdout_sinks.cpp
> |           |
> |           \---tests
> |                   catch.hpp
> |                   catch.license
> |                   CMakeLists.txt
> |                   includes.h
> |                   main.cpp
> |                   meson.build
> |                   test_async.cpp
> |                   test_backtrace.cpp
> |                   test_cfg.cpp
> |                   test_create_dir.cpp
> |                   test_daily_logger.cpp
> |                   test_dup_filter.cpp
> |                   test_errors.cpp
> |                   test_eventlog.cpp
> |                   test_file_helper.cpp
> |                   test_file_logging.cpp
> |                   test_fmt_helper.cpp
> |                   test_macros.cpp
> |                   test_misc.cpp
> |                   test_mpmc_q.cpp
> |                   test_pattern_formatter.cpp
> |                   test_registry.cpp
> |                   test_sink.h
> |                   test_stdout_api.cpp
> |                   test_systemd.cpp
> |                   utils.cpp
> |                   utils.h
> |
> +---Sandbox
> |   \---src
> |           SandboxApp.cpp
> |
> \---vendor
>     \---bin
>         \---premake
>                 premake5.exe
> ```
> 
> And this is the content from my _**premake5.lua**_ file:
> 
> ```
> workspace "Hazel"
> 	architecture "x64"
> 
> 	configurations
> 	{
> 		"Debug",
> 		"Release",
> 		"Dist"
> 	}
> 
> outputdir = "%{cfg.buildcfg}-%{cfg.system}-%{cfg.architecture}"
> 
> project "Hazel"
> 	location "Hazel"
> 	kind "SharedLib"
> 	language "C++"
> 
> 	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
> 	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")
> 
> 	files
> 	{
> 		"%{prj.name}/src/**.h",
> 		"%{prj.name}/src/**.cpp"
> 	}
> 
> 	includedirs
> 	{
> 		"%{prj.name}/vendor/spdlog/include"
> 	}
> 
> 	filter "system:windows"
> 		cppdialect "C++17"
> 		staticruntime "On"
> 		systemversion "latest"
> 
> 		defines
> 		{
> 			"HZ_PLATFORM_WINDOWS",
> 			"HZ_BUILD_DLL"
> 		}
> 
> 		postbuildcommands
> 		{
> 			("{COPY} %{cfg.buildtarget.relpath} ../bin/" .. outputdir .. "/Sandbox")
> 		}
> 
> 	filter "configurations:Debug"
> 		defines "HZ_DEBUG"
> 		symbols "On"
> 
> 	filter "configurations:Release"
> 		defines "HZ_RELEASE"
> 		optimize "On"
> 
> 	filter "configurations:Dist"
> 		defines "HZ_DIST"
> 		optimize "On"
> 
> project "Sandbox"
> 	location "Sandbox"
> 	kind "ConsoleApp"
> 	language "C++"
> 
> 	targetdir ("bin/" .. outputdir .. "/%{prj.name}")
> 	objdir ("bin-int/" .. outputdir .. "/%{prj.name}")
> 
> 	files
> 	{
> 		"%{prj.name}/src/**.h",
> 		"%{prj.name}/src/**.cpp"
> 	}
> 
> 	includedirs
> 	{
> 		"Hazel/vendor/spdlog/include",
> 		"Hazel/src"
> 	}
> 
> 	links
> 	{
> 		"Hazel"
> 	}
> 
> 	filter "system:windows"
> 		cppdialect "C++17"
> 		staticruntime "On"
> 		systemversion "latest"
> 
> 		defines
> 		{
> 			"HZ_PLATFORM_WINDOWS"
> 		}
> 
> 	filter "configurations:Debug"
> 		defines "HZ_DEBUG"
> 		symbols "On"
> 
> 	filter "configurations:Release"
> 		defines "HZ_RELEASE"
> 		optimize "On"
> 
> 	filter "configurations:Dist"
> 		defines "HZ_DIST"
> 		optimize "On"
> ```
> 
> Do anyone in this community knows where could be the problem or how could I approaching it?
> Thank you in advance for any comment!

i  had the same problem , how did you slove it
