### ISSUE TITLE
Should call layer->OnAttach() in 'PushLayer' and 'PushOverlay'

### ISSUE THREAD

**Issue by thewildnath** [TheCherno/Hazel#222]
https://github.com/TheCherno/Hazel/blob/3d5068b9bd665bc0030de4c6bb5b9745a2dd3171/Hazel/src/Hazel/Core/LayerStack.cpp#L15

**Comment by muthubro** [comment]
This used to be how it was done earlier. TheCherno later moved the OnAttach call to where the PushLayer call actually happens (in `Application::PushLayer`) as LayerStack is purely meant as a data structure to hold Layers.

**Comment by thewildnath** [comment]
Oh, I see. I'm following the tutorials but changing stuff to better suit me, so instead of a 'LayerStack' I made a 'LayerManager'. Thanks for the info and I guess I can close the issue.
