### ISSUE TITLE
SandBox.exe throwns exception 0x0000000000000000 when adding ImGui

### ISSUE THREAD

**Issue by RenierChaves** [TheCherno/Hazel#229]
ImGui doesn't run, he throws that exception. My graphics card supports only opengl 3.3. Do I need to support 4.5 to run or am I doing something wrong?

**Comment by IshoAntar** [comment]
> Do I need to support 4.5 to run

Yes you do!
Hazel requires at least an OpenGL 4.5-compatible GPU/driver

**Comment by RenierChaves** [comment]
Thank you!
