### ISSUE TITLE
DLL export/import

### ISSUE THREAD

**Issue by KSmigielski** [TheCherno/Hazel#23]
I wonder why you do not use Boost.DLL?
I think that this is a better solution since the engine is to be multi-platform.
It is a simple solution to implement.

**Comment by 3x3y3z3t** [comment]
I don't see any relation between Boost.DLL and DLL export/import. Does Hazel need to import other dll's function?
Currently Hazel is depends on other libraries, but all of them are either can be able to include directly into source code (spdlog) or can be linked statically (glfw, glad, imgui). Whichever platform we are distribute to, we only distribute a single library "Hazel", which contains everything in it.

**Comment by MaximPrime** [comment]
Yes, it is platform specific, but I don't know it is needed at this point
of dev since it is not supporting any other systems. But if you want, fell
free :)

niedz., 3 lut 2019, 13:30 użytkownik KSmigielski <notifications@github.com>
napisał:

**Comment by cubedtear** [comment]
I agree with @3x3y3z3t. Also, these `#define`'s are simple enough to be worth adding another dependency just for them.
In response to @KSmigielski and @MaximPrime, in the [PR #27: Add Linux support (updated)](https://github.com/TheCherno/Hazel/pull/27/files#diff-2f00fc3a8cdd3296b26e631b2d2a3b2aL3), the mentioned snippet has already been updated to work both on Windows and Linux.

**Comment by KSmigielski** [comment]
I understand that this is solved for Linux. But if there are plans for development for other systems, it is inefficient to write for each of them macro

**Comment by braxtons12** [comment]
> I understand that this is solved for Linux. But if there are plans for development for other systems, it is inefficient to write for each of them macro

@KSmigielski Adding another (assumingly rather large, considering it's from BOOST) dependency for something this trivial is against good practices. We can write the macros to accomplish this ourselves, likely with less code, just fine. Pulling in another dependency for what might amount to a grand total of 100 lines is ridiculous.

**Comment by 3x3y3z3t** [comment]
> Yes, Hazel need to import/export other dll's.
I'm sorry if it is just me, but considering the fact that currently Hazel depends on glfw, glad, imgui (which is being statically linked) and spdlog (source code is included), I don't see any need to import other dll's functions. Can you please give some example of external functions that Hazel need to import?

> When you look up at [/Hazel/src/Hazel.Core.h](https://github.com/TheCherno/Hazel/blob/master/Hazel/src/Hazel/Core.h)
> there is:
>
> ...
>
> Boost.DLL allow handle this whiout platform specifics code.
Those macro definitions is for exporting and importing of Hazel's own functions. It is not for import other dll's function.

Ass @braxtons12 said, we can write some macros to handle platform-specific part of code. Cherno have said to make the engine as less dependency as possible, not to say that we add a whole library just to use a small part of it.

**Comment by Gaztin** [comment]
Closing since no further discussion has taken place. Please reopen if you have more to add, @KSmigielski
