### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by stephend017** [TheCherno/Hazel#231]
#### Is your feature request related to a problem? Please describe
There is currently no documentation on the Hazel API and how to accomplish certain things in Hazel. This makes it harder for newer developers to both use and contribute to Hazel.

#### Describe the solution you'd like
Add documentation in the source code and public documentation on the repo wiki or hazel website.

#### Describe alternatives you've considered
n/a

#### Additional context
This is a feature that is and should be necessary for releases as well as helping new developers join the Hazel community

**Comment by LovelySanta** [comment]
We started building our own hazel wiki at this point, we just need content to be written, without some basic content, we can't really publish (after testing). Content should be written in markdown.

**Comment by stephend017** [comment]
Do you have a link to the wiki? I'd love to help write content if needed.

**Comment by destroyer449** [comment]
I have also started making a wiki but do not have the slightest idea of what to put in it. how should the hazel wiki be arranged?

**Comment by stephend017** [comment]
If I had to guess, I'd say it should be organized by feature or how to achieve certain things using the engine like rendering a quad or particles. This can be done through basic examples so developers and users alike know what's supported and how to use it.

**Comment by LovelySanta** [comment]
The wiki is located at https://github.com/TheChernoCommunity/HazelWiki. And I got a basic site working, we just need content to put on it: https://github.com/LovelySanta/HazelWiki and get github actions integrated in the deployment when pushing to master.

Our idea was to have an api-kinda look, so it acts like an api, with some additional documentation underneath each api class where needed.

**Comment by stephend017** [comment]
It looks like the site is ready for content, I think before that happens we should define a format for everything so it doesn't become messy.

**Comment by LovelySanta** [comment]
Maybe try creating an api for the event system as guidance? I do like how it is done here: 
https://wiki.factorio.com/Prototype/AssemblingMachine

a condensed table of the full api, click on it to go to details below it

**Comment by stephend017** [comment]
Sounds good I'll PR into [https://github.com/LovelySanta/HazelWiki](https://github.com/LovelySanta/HazelWiki) since [https://github.com/TheChernoCommunity/HazelWiki]( https://github.com/TheChernoCommunity/HazelWiki) is not up to date

**Comment by LovelySanta** [comment]
We still have to figure out how to auto deploy when pushed into master, hence why it's not into https://github.com/TheChernoCommunity/HazelWiki yet.

**Comment by stephend017** [comment]
there is an npm package [gh-pages](https://www.npmjs.com/package/gh-pages) which combined with travis or github actions should be able to achieve this.

**Comment by LovelySanta** [comment]
Feel free to setup a demo on your fork, so I can do it on my fork, and then push it to the community

**Comment by LovelySanta** [comment]
I'll close this for now. The wiki has it's own issue page that can take reports.
