### ISSUE TITLE
Why use glfw / OpenGL to implement imguilayer?

### ISSUE THREAD

**Issue by Tsingbing** [TheCherno/Hazel#233]
Why use glfw / OpenGL to implement imguilayer operation instead of using your own event distribution system? 
What's the difference between the two methods? 
Which is better?

**Comment by LovelySanta** [comment]
Cherno mentioned that ImGui will only be used for debugging purposes, so not integrated in the engine to be used in a released state. For this reason, ImGui is as stand-alone as possible as far as I know.

**Comment by Tsingbing** [comment]
Thank you very much for your answer!
