### ISSUE TITLE
linux support

### ISSUE THREAD

**Issue by andrewcz** [TheCherno/Hazel#24]
hi @TheCherno !
was wondering if this project will also be suitable for linux.
i honestly just cant afford a decent windows laptop.

Best,
Andrew

**Comment by DrBarnabus** [comment]
I would suggest you have a look at PR #27 this shows/discusses the necessary changes to make the project work on Linux.

**Comment by oj002** [comment]
Glfw, imgui and glad are crossplatform so the only thing you need to do is change up how to compile the project. The dllexport atuff works differently on linux

**Comment by Gaztin** [comment]
Closing since the question has been answered.
