### ISSUE TITLE
I've created a cmakelists file for hazel sort of... but i've renamed the whole engine.. and im using mingw gcc ... it can work in linux

### ISSUE THREAD

**Issue by tawandachiteshe** [TheCherno/Hazel#244]
#### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is, e.g. "I'm always frustrated when [...]"

#### Additional context
Add any other context or screenshots about the feature request here. Any relevant information for platform specific features could be useful.

**Comment by LovelySanta** [comment]
See #82 as we do want to generate the make files using premake. It also has info (in the readme) about the required packages.
