### ISSUE TITLE
Opengl2 support for machines with performances works on a igpus

### ISSUE THREAD

**Issue by tawandachiteshe** [TheCherno/Hazel#245]
#### Is your feature request related to a problem? Please describe
A clear and concise description of what the problem is, e.g. "I'm always frustrated when [...]"

#### Additional context
Add any other context or screenshots about the feature request here. Any relevant information for platform specific features could be useful.

**Comment by LovelySanta** [comment]
As cherno mentioned in his video, we only support OpenGL 4.5, nothing lower. I mention it a second time, please take the time to fill in the form instead of just providing a title.
