### ISSUE TITLE
I Fell For New Comers Add A Github Wiki!

### ISSUE THREAD

**Issue by Clickyz** [TheCherno/Hazel#255]
And Remember That For The Future :)

**Comment by LovelySanta** [comment]
Around 2 weeks ago we finished up the frame work for a community driven HazelWiki. There is currently no context other than some placeholders. You can find the wiki at thechernocommunity.github.io/HazelWiki which is hosted on github ([thechernocommunity/Hazelwiki](https://github.com/thechernocommunity/Hazelwiki)). Feel free to start contributing to it. There is a page about how to contribute.

**Comment by Clickyz** [comment]
> Around 2 weeks ago we finished up the frame work for a community driven HazelWiki. There is currently no context other than some placeholders. You can find the wiki at [thechernocommunity.github.io/HazelWiki](https://thechernocommunity.github.io/HazelWiki/) which is hosted on github ([thechernocommunity/Hazelwiki](https://github.com/thechernocommunity/Hazelwiki)). Feel free to start contributing to it. There is a page about how to contribute.

Ok Thanks
