### ISSUE TITLE
Premake building problem

### ISSUE THREAD

**Issue by 62bit** [TheCherno/Hazel#263]
This problem occurs when I try to build solution files.
> vendor\bin\premake\premake5.exe vs2019
Error: cannot open Hazel/vendor/GLFW: No such file or directory

**Comment by 9Y0** [comment]
You likely haven't cloned the submodules yet. Try running `git submodule init && git submodule update` in the root folder of Hazel. I would also recommend posting these "issues" in discord because you probably will get advice there faster, and it isn't really a issue with the Hazel project

**Comment by 62bit** [comment]
OH thank you so much it works. I'm sorry for this post, I will consider asking questions on discord. You can delete this if you can btw.
