### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by bonyet** [TheCherno/Hazel#275]
Hazel runs at 30 fps in the latest commit. glfwSwapBuffers() takes 20 ms according to my profiling.

1. Clone latest commit
2. Add some fps or frame time counter, you can use ImGui::GetIO().Framerate to get the framerate.
3. Build and run

You should see that the engine does not perform well.

- OS: Windows 10, 64-bit

Vsync has no effect on this

**Comment by bonyet** [comment]
I am sorry for wasting your time, this was all my bad.

**Comment by Fredkiss3** [comment]
Can you provide at least what Did you do to fix your problem ?

**Comment by bonyet** [comment]
> Can you provide at least what Did you do to fix your problem ?

Disable vsync in your gpu settings, or find a setting that works for you. I set it to "Let the 3D application decide" and it works like a charm

**Comment by csp256** [comment]
I had a similar problem as well, and it took me a while to figure out as it was the default behavior on my system.
