### ISSUE TITLE
Change Renderer2D QuadVertexPositions to a mat4 rather than vec4 array

### ISSUE THREAD

**Issue by Veeloxfire** [TheCherno/Hazel#278]
**Suggestion**
I know its a small thing but I just think that the code looks nicer as a mat4 rather than a vec4 array and all calculations will be mathematically the same as a 4x4 matrix multiplication is done per column(/row depending on which way it goes I cant remember which way it is in glm) and each column(/row) is the same as a vec4.

It allows the transforms to all be done in one go rather than per vec4 during the assignment

**Proposed changes**
Current QuadVertexPositions is written as `glm::vec4 QuadVertexPositions[4];` and initialized as 
```
s_Data.QuadVertexPositions[0] = { -0.5f, -0.5f, 0.0f, 1.0f };
s_Data.QuadVertexPositions[1] = {  0.5f, -0.5f, 0.0f, 1.0f };
s_Data.QuadVertexPositions[2] = {  0.5f,  0.5f, 0.0f, 1.0f };
s_Data.QuadVertexPositions[3] = { -0.5f,  0.5f, 0.0f, 1.0f };
```
Im suggesting it be written as `glm::mat4 QuadVertexPositions;` and initialized as 
```
s_Data.QuadVertexPositions = { { -0.5f, -0.5f, 0.0f, 1.0f },
                               {  0.5f, -0.5f, 0.0f, 1.0f },
                               {  0.5f,  0.5f, 0.0f, 1.0f },
                               { -0.5f,  0.5f, 0.0f, 1.0f } }
```
(although Im pretty sure the first initializing way works I just like to initialize objects in one go)

The the main reason I prefer this way is that the matrix multiplication can all be calculated before the for-loop. Im not sure this actually improves performance but I think it at least improves readability and makes the assignment more uniform for each layout element.

for example in the rotated quad function
```
glm::mat4 transform = glm::translate(glm::mat4(1.0f), position)
		    * glm::rotate(glm::mat4(1.0f), glm::radians(rotation), { 0.0f, 0.0f, 1.0f })
		    * glm::scale(glm::mat4(1.0f), { size.x, size.y, 1.0f });

for (size_t i = 0; i < quadVertexCount; i++)
{
	s_Data.QuadVertexBufferPtr->Position = transform * s_Data.QuadVertexPositions[i];
	...
}
```
becomes
```
glm::mat4 transformedPositions = glm::translate(glm::mat4(1.0f), position)
			* glm::rotate(glm::mat4(1.0f), glm::radians(rotation), { 0.0f, 0.0f, 1.0f })
			* glm::scale(glm::mat4(1.0f), { size.x, size.y, 1.0f })
                        * s_Data.QuadVertexPositions;

for (size_t i = 0; i < quadVertexCount; i++)
{
	s_Data.QuadVertexBufferPtr->Position = transformedPositions[i];
	...
}
```
**Final Thoughts**
Im pretty sure the maths checks out and the preliminary testing I've done doesnt seem to change any functionality and seems to at least be the same performance although I havent done a definetive stress test to see if there is a performace change. Intuitavely it seems like it should improve speed but at the very least its handing over the responsibility to glm.

Im happy to make a pull request if people think its worth it. Its not exactly a large change

Im sorry if this has been suggested before but I had a little look and didnt see it anywhere

there might be a way to replace one of the `glm::mat4(1.0f)`s with `s_Data.QuadVertexPositions` which should remove a matrix multiplication but I havent tried that

**Comment by LovelySanta** [comment]
I don't believe there is a performance benefit in this. Calculating 4x vex4's versus calculating 1x mat4 will yield the same calculations, but in your case you'll have to index your mat4 again to extract the vec4 out of it, it might even be worse.. I really don't see a readable difference...
