### ISSUE TITLE
Dependency Build Paths

### ISSUE THREAD

**Issue by DrBarnabus** [TheCherno/Hazel#28]
At present the dependencies for the project (GLFW, GLAD and ImGui) are building into their own sub folders inside vendor.

I was unsure if this was intended or not, but in the case that it wasn't intended the following changes could be made to the dependencies premake5.lua files to fix the issue.

```lua
targetdir ("%{wks.basedir}/bin/" .. outputdir .. "/%{prj.name}")
objdir ("%{wks.basedir}/bin-int/" .. outputdir .. "/%{prj.name}")
```

A number of other changes could be made to their premake files as well to keep them in line with the main project's setup such as the staticruntime, runtime, symbols, systemversion "latest" and optimization options.

I can create pull requests for this change in the relevant repositories if anyone else thinks this is worth changing.

**Comment by SeppahBaws** [comment]
Since the dependency projects are being statically linked into the main Hazel DLL we're probably never going to have to access them individually, so I don't see the need to put them together in the main bin/ folder.
That's just my thought...

**Comment by DrBarnabus** [comment]
Alternatively, perhaps we could add the bin/bin-int folders inside those sub-projects to the .gitignore.

This would at least stop git from complaining there are un-tracked or unmodified files in the sub modules.

**Comment by DrBarnabus** [comment]
Thinking about it, they are already being ignored in the .gitignore thanks to bin/ and bin-int/.

Going to close this off, as I can see the reasoning behind it as @SeppahBaws suggested.
