### ISSUE TITLE
Textures not rendering on some AMD graphics cards

### ISSUE THREAD

**Issue by ayoubdevgg** [TheCherno/Hazel#282]
hazel only render black quads and gray background

**Comment by LovelySanta** [comment]
Can you reproduce this in the current state of Hazel? We did fix some AMD issues some weeks ago. Cherno mentioned it in one of his videos prior to starting the ECS. See PR #247 in particular that fixed issues reported in #238. Some just had artifacts, others had black quads. They all reported it fixed after that. Does this help you as well?

**Comment by ayoubdevgg** [comment]
today commit fixed the problem with the black quads i can render the green quad but no textured ones

**Comment by ayoubdevgg** [comment]
i have very old AMD card 2010 i tried the beta drivers and the problem is solved
