### ISSUE TITLE
Compile issue in Entity class due to conversion error

### ISSUE THREAD

**Issue by balsigergil** [TheCherno/Hazel#284]
#### Describe the bug

Project doesn't compile.

Compiler output
```
Hazel\Hazel\src\Hazel\Scene\Entity.h(43,49): error C2676: binary '!=': 'const entt::entity' does not define this operator or a conversion to a type acceptable to the predefined operator (compiling source file src\EditorLayer.cpp)
```

#### To Reproduce
1. Re-clone the entire project from GitHub
1. Try to compile :)
2. See error above

#### Screenshots
https://github.com/TheCherno/Hazel/blob/5658efcc6b91c02c8a6528bdd6f89ef5347fae4f/Hazel/src/Hazel/Scene/Entity.h#L43

Type conversion error :
![2020-07-23 14_19_15-Window](https://user-images.githubusercontent.com/24603909/88285537-91960700-ccef-11ea-8c9c-c9fb90c8802c.png)

#### Operating system:
- OS: win-64
- Version: Windows 10 home

#### Proposed fix
In PR #285

**Comment by Fredkiss3** [comment]
In entt docs in order to test if an entity is valid, they recommend either to use 
```cpp
entt::registry.valid(entityHandle);
```

Or compare the entity with `entt::null`

```cpp
entityHandle != entt::null;
```

**Comment by balsigergil** [comment]
Sure, that's a better and cleaner solution. I'll modify the PR.

**Comment by Fredkiss3** [comment]
In the meantime, `entityHandle` should be initialized to `entt::null` in the wiki it is said that `entt::null `and `entt::entity { 0 }` are different event through there are both invalid entities

**Comment by Fredkiss3** [comment]
https://github.com/skypjack/entt/wiki/Crash-Course:-entity-component-system#null-entity

**Comment by LovelySanta** [comment]
Already talked about this in Discord as I noticed this while watching the video. This is indeed correct!

**Comment by ayoubdevgg** [comment]
i tried this and it worked

operator bool() const { return &m_EntityHandle != 0; }

**Comment by balsigergil** [comment]
@ayoubdevgg You are comparing the address of `m_EntityHandle` with 0 so it compiles because an address is an integer but I'm not sure that's the expected behavior. entt::entity is already an integer and we just need to cast it to make it compiles and work as intended.

These 2 solutions work :
```cpp
// C style cast
operator bool() const { return (int)m_EntityHandle != 0; }
```

```cpp
// C++ style cast
operator bool() const { return static_cast<int>(m_EntityHandle) != 0; }
```

**Comment by LovelySanta** [comment]
That won't work @balsigergil. Refering back to https://github.com/TheCherno/Hazel/issues/284#issuecomment-663003893, the `entt::entity` with enum representation `0` is NOT the same as `entt::null`. The current implementation is perfect.

**Comment by OverShifted** [comment]
@balsigergil I think casting to ```uint32_t``` is better because entity is:
```cpp
enum class entity: id_type;
```
```cpp
/*! @brief Alias declaration for type identifiers. */
using id_type = ENTT_ID_TYPE;
```
```cpp
#ifndef ENTT_ID_TYPE
#   include <cstdint>
#   define ENTT_ID_TYPE std::uint32_t
#endif
```

**Comment by LovelySanta** [comment]
#285 fixes this like the wiki suggests (see https://github.com/TheCherno/Hazel/issues/284#issuecomment-663003893).
![image](https://user-images.githubusercontent.com/26593477/88466002-39fec380-cec8-11ea-85c6-719307923e9d.png)
