### ISSUE TITLE
Building solution

### ISSUE THREAD

**Issue by seremempire** [TheCherno/Hazel#308]
This repo his hard to implement on visual studio. To the developer do consider using build tools like Cmake or Scons for automatic analyzes source code file dependencies to aid in making solutions.

**Comment by LovelySanta** [comment]
We do use premake for this. Premake generates VS files for windows, but is also capable of creating make files for eg linux platforms, for those that whish to follow along there. I do not see why additional cmake support should be added?

**Comment by abhinav3967** [comment]
Premake can be compiled on linux but it is giving error that linux isn't supported. i think it is because of this line`#error "Linux is not supported!"` in Hazel/src/Hazel/Core/Base.h

**Comment by LovelySanta** [comment]
That's because Hazel does not officially support Linux yet. There is a PR to add it in. Minor tweaks have to be done for that, however that's too big of a topic to just merge with a PR. Cherno should do that in a video.

**Comment by jarlah** [comment]
<img width="1050" alt="Screenshot 2020-09-09 at 15 39 35" src="https://user-images.githubusercontent.com/404102/92606020-c1569980-f2b2-11ea-979b-cd0d40374caa.png">

not sure how far I will get with this, but if anyone is interested I am currently going to non windows, non visual studio and non limited to windows route. Guess ill be stuck at some point when I have to use something uber specific library for windows ...

**Comment by jarlah** [comment]
I must admit that i am a senior Developer. But in the small beginnings there is literally nothing stopping us from using both macOS, eclipse and premake5 gmake

**Comment by LovelySanta** [comment]
I'll close this as this is not an issue as I stated before. Currently we only support visual studio, but premake is capable of creating makefiles for Linux as demonstrated in #82.
