### ISSUE TITLE
A minor issue with extra warnings as errors

### ISSUE THREAD

**Issue by Feacur** [TheCherno/Hazel#32]
Just saying, if you setup high level of warnings like
```
# which I did
warnings "Extra"
flags { "FatalWarnings" }

# or something like
filter "toolset:msc*"
    buildoptions { "-W4", "-WX" }
```

Then you need also these:

> Core.h
```
#ifdef HZ_PLATFORM_WINDOWS
	#ifdef HZ_BUILD_DLL
		#define HAZEL_API __declspec(dllexport)
		#define HAZEL_TEMPLATE
	#else
		#define HAZEL_API __declspec(dllimport)
		#define HAZEL_TEMPLATE extern
	#endif
#else
	#error Hazel only supports Windows!
#endif
```

> Log.h
```
HAZEL_TEMPLATE template class HAZEL_API std::shared_ptr<spdlog::logger>;
```

> Application.h
```
HAZEL_TEMPLATE template class HAZEL_API std::_Compressed_pair<std::default_delete<Window>, Window *, true>;
HAZEL_TEMPLATE template class HAZEL_API std::unique_ptr<Window>;
```

Which is mostly compiler nonsense, I would say.

Random search on the warning gives: https://jeffpar.github.io/kbarchive/kb/168/Q168958/

**Comment by Gaztin** [comment]
I think Extra warnings are a great idea, but fatal warnings might not be the best in this situation considering a lot of people are going to get frustrated at petty stuff when they're just trying out stuff or playing around with the codebase.
That said, I suggest you open a PR so we can take this discussion further!

**Comment by LovelySanta** [comment]
Closing this as this is not relevant anymore, the current base has no warnings, as mentioned in PR 26 (linked above), this is all fixed on cherno's request already. If it is needed in the future, we can always add it in later.
