### ISSUE TITLE
Why do we have PICSEL_PROFILE_SCOPE_LINE and PICSEL_PROFILE_SCOPE_LINE2

### ISSUE THREAD

**Issue by feresr** [TheCherno/Hazel#331]
Is there anything I'm missing here? Why do we have `PICSEL_PROFILE_SCOPE_LINE2`

https://github.com/TheCherno/Hazel/blob/857d8d60e63b23c67edf1bb10e2715fb57089597/Hazel/src/Hazel/Debug/Instrumentor.h#L232

**Comment by LovelySanta** [comment]
It is there in order to expand the `__LINE__` argument

**Comment by feresr** [comment]
Will do. I often ask questions there, I honestly thought this was something we overlooked. since it works with out that second macro for me
