### ISSUE TITLE
Android project

### ISSUE THREAD

**Issue by goldspark** [TheCherno/Hazel#338]
How would I transfer this to android project? That is what code would I write so Hazel Engine outputs apk file?

I want at least a screen with quad in the middle to be the demo for apk output. From there I can get other things by myself.

It would be awesome to use Hazel to develop Android games and apps.

**Comment by babaliaris** [comment]
Hazel does not support it yet. It's a LOT of work to do it by yourself, even if you know what you're doing. You must integrate the android SDK into Hazel, implement the android windowing system and event system (well android does not have windows but something that they call Activities). Then you also need to implement the render API that android uses, I believe it's Vulcan these days.

**Comment by LovelySanta** [comment]
For further questions, I kindly ask to go to [TheCherno's discord](https://discord.gg/K2eSyQA) and ask your questions there in the **#game-engine-dev** channel.
