### ISSUE TITLE
A project called “Hazel” already exists.

### ISSUE THREAD

**Issue by somerandomdev49** [TheCherno/Hazel#345]
> If someone already created an issue about this, then sorry :(

Here is the link to the project: https://github.com/hazelgrove/hazel
This repo was created on 2017-01-27, as the github API says. (https://api.github.com/repos/hazelgrove/hazel#created_at) This project is **very** actively developed, so something needs to be done about it.

**Comment by LovelySanta** [comment]
They are both about different things, so I don't really see an issue here?

**Comment by somerandomdev49** [comment]
Well, the name is the same so there can be some issues, I don't know really :)

**Comment by LovelySanta** [comment]
Well, maybe in the future something comes up, but it's to be expected that something, somewhere is called the same as something else, as long as they don't interfear it's all fine, and that seems to be the case for now.. I'll close this for now as this is not a big issue atm...
