### ISSUE TITLE
The collision system will soon be implemented in Hazel ?

### ISSUE THREAD

**Issue by yassinrais** [TheCherno/Hazel#368]
Hello Hazel team :) 
i just want to know if 
Its is possible to implement an 2D Collision system ?

thanks.

**Comment by OverShifted** [comment]
Hi.
I don't know why you are asking it and asking it here, but YES (obviously) I have 2D physics in my game engine [OverEngine](https://github.com/OverShifted/OverEngine) which looks like Hazel (not a fork) I am using [Box2D](https://box2d.org/) ([Or Github](https://github.com/erincatto/box2d))

**Comment by yassinrais** [comment]
No I mean integred in Hazel , a hazel one

**Comment by OverShifted** [comment]
I have no idea what are you talking about.
It's like asking `is it possible to connect the mouse to my new gaming laptop?`
It is currently impossible and NASA is trying to figure out how to implement that by investing billions of dollars in this.
then me, Unity, Unreal, and many other games and engines, steal that technology and used it in our software.

**Comment by yassinrais** [comment]
Bro! Question to easy, 
does hazel will have he is own collision system or not, 

what did you not understand about my question?

i dont care about other library , i m talking about the Hazel

**Comment by AnantTiwari-Naman** [comment]
> Bro! Question to easy,
> does hazel will have he is own collision system or not,
> 
> what did you not understand about my question?
> 
> i dont care about other library , i m talking about the Hazel

I do not understand why you can't understand jokes. YES, I think it was obvious that we certainly can implement collision detection. Hazel is a game engine and for even a bad game engine i think you NEED a collision detection system. I don't understand why you had to even ask this question.

**Comment by yassinrais** [comment]
he is jockes became to toxic ! 🤮 

I m asking if this is will be added to hazel or not  ❓ 

easy question 🌾  , and yeah easy answer 💨  yes/no 👍🏻

**Comment by AnantTiwari-Naman** [comment]
> he is jockes became to toxic ! 🤮
> 
> I m asking if this is will be added to hazel or not ❓
> 
> easy question 🌾 , and yeah easy answer 💨 yes/no 👍🏻

Yes.

**Comment by yassinrais** [comment]
Thanks for you understanding!

**Comment by theParsa** [comment]
bruh moment

**Comment by AnantTiwari-Naman** [comment]
Yeah I think this issue should also be closed.
