### ISSUE TITLE
yaml-cpp build errors on MacOS

### ISSUE THREAD

**Issue by Pikachuxxxx** [TheCherno/Hazel#369]
#### Describe the bug
Encountering multiple semantic and parsing issues while trying to build Hazel on MacOS. 

![Screenshot 2020-11-19 at 11 17 42 AM](https://user-images.githubusercontent.com/45527623/99626837-181de380-2a59-11eb-8df6-8d8926c39a7d.png)

#### To Reproduce
Build the engine using the premake 
And once you get the Xcode workspace try building the libraries and that will result in the following errors

#### Expected behavior
Expected to build the engine without any compatibility errors

#### Operating system: (please complete the following information)
- OS: MacOS
- Version: BigSur

**Comment by Pikachuxxxx** [comment]
So I manually set the language dialect to c++11 in yaml-cpp project but nothing happens, even the headers search paths for other vendor dependencies seems to be broken in the project files. I think the fact that premake supports only Xcode4 is a potential drawback. Despite the fact The Cherno explicitly explained the advantages of premake, I think using having CMake as an alternative build system would solve this issue. Any advice on running hazel on Mac would be very helpful.

**Comment by LovelySanta** [comment]
Currently they are working on implementing linux in Hazel-dev. I assume macOS afterwards. You might have more response if you ask these questions in thecherno discord, instead of creating an issue here.

**Comment by Pikachuxxxx** [comment]
Yeah sure, I will close this for now and take it to discord. Thanks for the update on current progress.
