### ISSUE TITLE
Make the wiki editable

### ISSUE THREAD

**Issue by mandar1jn** [TheCherno/Hazel#375]
Could you please give us the ability to edit the wiki? I wanted to add a how to build page, but I can't edit it and when forking it it doesn't fork the wiki

**Comment by mandar1jn** [comment]
[download the source.txt](https://github.com/TheCherno/Hazel/files/5607471/download.the.source.txt)
just as an example. I couldn't upload a md file

**Comment by MMS-27** [comment]
The Wiki is Being Edited at the Cherno Community Repository . Please Check that One There

**Comment by LovelySanta** [comment]
I'll close this as duplicate of #353
See https://github.com/TheCherno/Hazel/issues/353#issuecomment-715925011 for more information, you can create a PR to the community repository with your contribution. It would be highly appreciated!
