### ISSUE TITLE
Follow your video and make cmake verison of my code which can run on different platform

### ISSUE THREAD

**Issue by rocketman123456** [TheCherno/Hazel#377]
`https://github.com/rocketman123456/RocketGE`

this is my repository, and i'm currently follow your video to study how to make a game engine.

I convert your code to run with cmake and support macos.

Thank you very much for your video series, that helps a lot!

**Comment by mandar1jn** [comment]
I don’t see how this is an issue. The cherno has already said that he won’t use cmake and that if needed premake can generate cmake files.

**Comment by rocketman123456** [comment]
actually, i want to leave this comment below the YouTube channel, but because of the GFW, i can't do it, so i write it here

> I don’t see how this is an issue. The cherno has already said that he won’t use cmake and that if needed premake can generate cmake files.

**Comment by mandar1jn** [comment]
The please don’t make a issue for it.

**Comment by LovelySanta** [comment]
You can always join [Cherno's discord](https://thecherno.com/discord) and send him a message in the `#cherno` channel. Alternatively you can find him on [twitch.tv/thecherno](https://twitch.tv/thecherno) and send him a live message. I'll close this as this is not a real issue as mentioned before.
