### ISSUE TITLE
Using default destructors over empty ones

### ISSUE THREAD

**Issue by RohacekD** [TheCherno/Hazel#38]
You are using empty destructors for your interfaces. This is potentially performance bug since class which is not `std::is_trivially_destructible<A>::value`. This is usually not a problem, but IMHO it is better to explicitly use default instead of empty destructors. Example of it is Window class.

**Comment by Gaztin** [comment]
If you know the solution to the issue, I'd appreciate it if you could submit a PR for it!

**Comment by IronicallySerious** [comment]
I am not sure, isn't this something compilers optimize by themselves?

**Comment by IronicallySerious** [comment]
This seems like there must have been a code design decision behind this. People often like to leave their destructors empty just for completeness' sake too.

**Comment by Gaztin** [comment]
This is something compilers sometimes cannot optimize. See https://www.youtube.com/watch?v=D8eCPl2zit4

**Comment by RohacekD** [comment]
Sorry, cannot watch video just now, but AFAIK they cannot due to language specification. From what I remember from"Modern C++ - Scott Meyers"

**Comment by RohacekD** [comment]
But I can agree that it is more of design decision/code guidelines thing than just creating PR.

**Comment by WhoseTheNerd** [comment]
You mean `~Window() = default;`?
