### ISSUE TITLE
Crash when changing gizmos while using them

### ISSUE THREAD

**Issue by Masterride05** [TheCherno/Hazel#383]
#### Description
Found an issue, if you change gizmos while using it, it will crash

#### My fix
i fixed it by locking the changing when i use it. not the best but it works
Im opening this issue, because i know that my fix is not the best and can be improved

#### Reproduce
To Reproduce: Try moving an object and change the gizmos to rotation / scale while you're moving it

**Comment by mandar1jn** [comment]
Can confirm
