### ISSUE TITLE
Crash selecting Object without a camera

### ISSUE THREAD

**Issue by Masterride05** [TheCherno/Hazel#387]
#### Description
Crash when selecting Object and pressing 'W', 'E' or 'R', while there is no camera in the scene and your cursor is on the viewport

#### To Reproduce
1. Open new scene
2. Create a new empty entity
3. Click on the entity
4. Press W, E or R inside the viewport
Note: no camera should be present

#### Expected behavior
(on visual studio) The program should crash and open "vector" at line 1484 at 
`_NODISCARD size_type size()`

**Comment by mandar1jn** [comment]
Can confirm

**Comment by LovelySanta** [comment]
This is fixed in https://github.com/TheCherno/Hazel/commit/96c57dadf5c3616ba3613034dfb63d3918590359 by adding an editor camera. In runtime, there is no editor camera, but then there are no imguizmo's either
