### ISSUE TITLE
Texture Index bug in Renderer2D + perspective cam

### ISSUE THREAD

**Issue by grashwandir** [TheCherno/Hazel#397]
#### Describe the bug
2D Texture get switched between sprites when perspective camera zoom in/out.
It cause a flickering of the textures.

#### To Reproduce
- setup a scene with at least 2 textured sprites 
- use perspective camera

Sorry for not describing it more, but the fix is really tiny; and I think Cherno will change everything in the 2D renderer in the futur.

So, jump to solution :)

In Texture.glsl, the issue is the v_TexIndex (which already caused trouble...) which -according to OpenGL docs- is not supposed to come from a vertexBuffer (there was another issue about this on github, but I can't find it again).

v_TexIndex is a float, and I guess (because I don't know how to output debug var from a Shader) that some times its value got slightly interpolated for whatever reason, and then truncate to int (in order to use it in the switch statement) round it down to the wrong texture slot (0.999999 get rounded to 0).

And indeed if I really round the number to the closest integer, the problem is gone and no more flickering!
...
	int texIndex = int(sign(v_TexIndex) * float(abs(v_TexIndex)+0.5));
	switch(texIndex)
	{
...

Sorry for the rough explanation, bad english, and unclear guesses. But it took me a long time to find this one, so in case it helps someone...

**Comment by LovelySanta** [comment]
Could you check if the current state of Hazel still has that issue after I merged #362?
If that didn't solve it, maybe we should pass it as an integer as described in #379 (which is not yet merged)? Could you check if that fixes it in that case?

**Comment by grashwandir** [comment]
Yes 'flat float' does the trick, and much better than rounding a float in a fragment shader =)
I am quite a newbie to OpenGL, thank you for the elegant solution.
