### ISSUE TITLE
Hazelnut not responding

### ISSUE THREAD

**Issue by MohitSethi99** [TheCherno/Hazel#405]
#### Describe the bug
Hazelnut becomes unresponsive when focused on console window and logs are being printed even after bringing back focus to Hazelnut.

#### To Reproduce
1. Clone master branch.
2. Build project.
3. Run Hazelnut.
4. Click two times on console window to bring it in focus.
5. Go back to Hazelnut and do something which triggers log (example: add same component two times to same entity).
6. Hazelnut would freeze.

#### Expected behavior
Hazelnut should not freeze and log should print in the console but nothing happens.

#### Screenshots
Video attached.

#### Operating system: (please complete the following information)
- OS: win-64
- Version:  Windows 10 Pro

https://user-images.githubusercontent.com/29519295/103276704-434b0980-49ed-11eb-9da5-74d340a9e88c.mp4

**Comment by twarug** [comment]
I think it's becouse you have focused cursor so the consol is freezed by Windows and waits for your input. It's normal behaviour.

Solution:
Press Enter in cosole.

**Comment by MohitSethi99** [comment]
Oh! Got it, thanks.
