### ISSUE TITLE
CreateApplication is declared Twice!

### ISSUE THREAD

**Issue by MrBrN197** [TheCherno/Hazel#41]
Why is `Application* CreateApplication()` declared twice both in **Application.h** and **EntryPoint.h**. Shouldn't we just have it declared once then implemented by the Sandbox Application.

**Comment by Husamdababneh** [comment]
this is not declaration in the way you think of ...
`extern Hazel::Application* Hazel::CreateApplication();`

'extern' tells the compiler that object is defined somewhere else ... as if you included the header that construct that object ... 

"they are the same object"

Best regards.

**Comment by MrBrN197** [comment]
but why do we need to say tell the compiler it's defined somewhere else. We already have a declaration of it in Application.h. The compiler already knows of it's existence

**Comment by Husamdababneh** [comment]
It's not like this  .. i recommend you to watch the compiler and linker videos which TheCherno did on his c++ series ... in little words ... the compiler "translate" each cpp file independently ... the content of a file which is included such as "iostream" is just copied to that file before it's compiled in a process called "pre-process" ... so in conclusion a cpp file it's aware of anything that isn't defined in it's own scope ...

so in our case we could include "Application.h" in "EntryPoint.h" or just tell the compiler that there is a declaration

**Comment by MrBrN197** [comment]
@Husamdababneh Did you delete your comment. I got an email saying you replied but I don't see it

**Comment by Mark-Linton** [comment]
> 
> 
> but why do we need to say tell the compiler it's defined somewhere else. We already have a declaration of it in Application.h. The compiler already knows of it's existence

You have to hell the compiler it's somewhere else because Hazel::CreateApplication() is also called inside EntryPoint.h. Declaring it as extern saves having to include Application.h in Entrypoint.h which would also include all the header files Application.h includes and the headers those headers include.

**Comment by ByteWrangler** [comment]
Ok that makes sense to me. On the other hand, client applications import Hazel.h which imports both Application.h and EntryPoint.h. So Application.h and EntryPoint.h end up in the same translation unit.

**Comment by Dragon9815** [comment]
@Mark-Linton If you want to use EntryPoint.h as a standalone file, there should probably be a foward declaration of the Application class:
```
class Application;
extern Hazel::Application* Hazel::CreateApplication();
```
Without this, it doesn't make sense to write a declaration which only compiles, if Application.h header is included before EntryPoint.h in the client application.

**Comment by MrBrN197** [comment]
@Mark-Linton I agree with what your saying but like @ByteWrangler said, `Application.h` is already being included. so we are not saving anything; and if we are using only stand-alone `EntryPoint.h` @Dragon9815  says we should declare Application before hand. 
Both of these ideas make sense but for both we are either adding an unnecessary declaration or missing a necessary declaration.
Why don't we either go with @Dragon9815 idea and add the `class Application;` declaration or go leave it as it is and remove the `extern Hazel::Application* Hazel::CreateApplication();` declaration.

**Comment by Mark-Linton** [comment]
> 
> 
> Ok that makes sense to me. On the other hand, client applications import Hazel.h which imports both Application.h and EntryPoint.h. So Application.h and EntryPoint.h end up in the same translation unit.

I agree with you, but hypothetically, what if a developer decides not to include hazel.h in favor of only including the headers for components they are going to use. Should each source/header file not be written so that it works as is without some include that the developer doesn't know exists. To understand what I'm trying to say... Look at EntryPoint.h, it's using the logging macros. Macros that only work because log.h is included elsewhere in a file that just happens to be processed before EntryPoint.h.

**Comment by MrBrN197** [comment]
> T

We understand this but what we are saying is that if your including EntryPoint.h then you must be using Application.h anyways. so now one would ever use EntryPoint.h by itself; it just doesn't make sense to do so from a user's point of view.

**Comment by TheCherno** [comment]
It's not exactly a declaration as others have pointed out (`extern`), but yes you're probably right, there's no need for it to be "declared" again since Application.h is included by the client. Unless anyone has any other thoughts, I'll probably remove it from `EntryPoint.h` soon.

**Comment by MrBrN197** [comment]
@TheCherno Thanks for clearing it up. I removed it from my version and it didn't make any difference; I thought you put it there for something in the future that I didn't fully understand.
