### ISSUE TITLE
Separate branch for Linux port

### ISSUE THREAD

**Issue by Horki** [TheCherno/Hazel#410]
#### Is your feature request related to a problem? Please describe
It would be cool to have a separate branch for the Linux port (experimental)

#### Describe the solution you'd like
I would like to port Hazel into the Linux platform, it would take several increments to have a (semi) working version.
Is it ok to start with porting? I would give my best that it can be compatible with Windows

**Comment by SeppahBaws** [comment]
There is already a big pull request going on for Linux support (#82), so I would suggest checking that out and if you want to do some additional porting work you can create a pull request in LovelySanta's fork.

**Comment by LovelySanta** [comment]
I'll close this as @SeppahBaws answered it correctly, and it should come to master eventually in some videos. For now it stays in my fork alone (or any other fork)
