### ISSUE TITLE
Sandbox App crashes on boot.

### ISSUE THREAD

**Issue by lochnessdragon** [TheCherno/Hazel#414]
#### Describe the bug
When loading the default Sandbox application, it crashes as ImGui cannot find the font file.

#### To Reproduce
1. Run the default Sandbox Application

#### Expected behavior
Run normally with the checkered background and quads.

#### Screenshots
N/A

#### Operating system: (please complete the following information)
- OS: win-64
- Version: Windows 10 home

**Comment by DaveAxiom** [comment]
This is a repeated issue of #380 .
