### ISSUE TITLE
Vendor folder not present

### ISSUE THREAD

**Issue by AlexandruIstrate** [TheCherno/Hazel#44]
I have noticed that the _vendor_ folder, at the solution's root is missing. It's the folder supposed to contain _premake5.exe_, which gets called by the _[GenerateProjects.bat](https://github.com/TheCherno/Hazel/blob/master/GenerateProjects.bat)_ file, in order to create the Visual Studio project files. I was curious whether it's like this on purpose, or whether the _.[gitignore](https://github.com/TheCherno/Hazel/blob/master/.gitignore)_ hides it, by accident, by specifying _bin/_ as an ignored directory.
Without the _premake_ executable, you have to download it and then put it in the required folder, in order to be able to generate the project files.

**Comment by DaveAxiom** [comment]
You must download premake for your system. The modules are missing when a regular `git clone <URL>` is executed. You must run `git clone --recursive <URL>` to populate the submodule directories. I added these instructions and more in the [Linux support pull request](https://github.com/cubedtear/Hazel).

**Comment by AlexandruIstrate** [comment]
So it's because you have to download the Premake binary for your platform. I understand.
