### ISSUE TITLE
yaml crash on fresh build: mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug'.

### ISSUE THREAD

**Issue by aadipoddar** [TheCherno/Hazel#457]
Hey I am getting a bunch of errors in the Hazel Engine when I added Python and Vulkan I am Listing down some of these errors can someone help me in solving it
![image](https://user-images.githubusercontent.com/83405769/126068447-f71b061f-2ea3-456d-8c88-b6875d384059.png)

**Comment by Pikachuxxxx** [comment]
Try turning static runtime off for yaml premake file

**Comment by LovelySanta** [comment]
See https://github.com/TheCherno/yaml-cpp/pull/1 for the fix. I'll leave this open until fixed.

**Comment by yuzeki** [comment]
> See [TheCherno/yaml-cpp#1](https://github.com/TheCherno/yaml-cpp/pull/1) for the fix. I'll leave this open until fixed.

It worked, thanks

**Comment by aadipoddar** [comment]
Thank you so much it worked out

**Comment by focusright** [comment]
Set all the dependencies' (Glad, GLFW, ImGui, yaml-cpp) project properties -> C/C++ -> Code Generation -> Runtime Library = Multi-threaded DLL (/MD)
