### ISSUE TITLE
gcc compile glfw makefile error "'cc' is not recognized as an internal or external command, operable program or batch file."

### ISSUE THREAD

**Issue by N00TN00T** [TheCherno/Hazel#46]
Hi,

I'm trying to set the project up with gcc, but when I try to compile the glfw makefile generated with the premake script in the forked repository, I get the error "'cc' is not recognized as an internal or external command, operable program or batch file.". However, it compiles fine if I generate visual studio files and compile with visual studio. 

I'm on windows 10, using cygwin to compile with gcc version 7.4.0.

**Comment by gold604** [comment]
Try to create an alias 'cc' to the gcc binary.
