### ISSUE TITLE
Build fails if Hazel folder path contains spaces (missing "")

### ISSUE THREAD

**Issue by LostInCompilation** [TheCherno/Hazel#460]
When building with VisualStudio, project "Premake" build fails with this error:
```
5>Regenerating project files with Premake5!
5>'G:\Path' is not recognized as an internal or external command, operable program or batch file.
5>Microsoft.CppCommon.targets(155,5): error MSB3073: The command "G:\Path with spaces\Hazel\vendor\premake\bin/premake5 vs2019 --file="G:\Path with spaces\Hazel\premake5.lua"
5>Microsoft.CppCommon.targets(155,5): error MSB3073: :VCEnd" exited with code 9009.
5>Done building project "Premake.vcxproj" -- FAILED.
```

This can be fixed if the PostBuild Command from the Premake project gets changed from this
`$(ProjectDir)bin/premake5 vs2019 --file="$(SolutionDir)premake5.lua"`

to this
`"$(ProjectDir)bin/premake5" vs2019 --file="$(SolutionDir)premake5.lua"`

Maybe include the change directly in the premake config files for the next update?

**Comment by Pikachuxxxx** [comment]
I've already made a pull, #449 , it's better to use \" token for uniformity. Damn these white spaces
