### ISSUE TITLE
The code execution cannot proceed because shaderc_sharedd.dll was not found

### ISSUE THREAD

**Issue by Noice75** [TheCherno/Hazel#463]
#### Error :-  The code execution cannot proceed because shaderc_sharedd.dll was not found. Reinstalling the program may fix this problem

I was following the hazel series and i got this bug so i tried to download the solution from github and i got the same error (The Solution is downloaded from [Hazel-content-browser Branch](https://github.com/TheCherno/Hazel/commit/c184dd2ecd5d87cfeb3b521c7c88e9b85f7dd7a9))

#### Screenshots
![Screenshot (925)](https://user-images.githubusercontent.com/84794374/127594149-ee2a8d82-ef45-4277-a377-05dd1a5ec0fc.png)

No changes are made to the code except to fix yaml and sandbox runtime issue which is mentioned [Here](https://github.com/TheCherno/Hazel/issues/457)

#### Operating system
- OS: [win-64]
- Version: [Windows 10 home]

**Comment by IshoAntar** [comment]
Make sure the file is in the executable's directory (same directory as the .exe)

**Comment by Noice75** [comment]
> Make sure the file is in the executable's directory (same directory as the .exe)

Which files can you specify them ? And i have downloaded the solution from github and havent changed any files

**Comment by IshoAntar** [comment]
The `shaderc_sharedd.dll` file, which should be under `Hazel\vendor\VulkanSDK\`
Just copy-paste it to the same directory as the .exe file.

**Comment by Noice75** [comment]
> The `shaderc_sharedd.dll` file, which should be under `Hazel\vendor\VulkanSDK\`
> Just copy-paste it to the same directory as the .exe file.

Yah it worked, Thanks

**Comment by IshoAntar** [comment]
Glad i could help :)
