### ISSUE TITLE
readpixel less than -1

### ISSUE THREAD

**Issue by realjf** [TheCherno/Hazel#465]
Describe the bug
![image](https://user-images.githubusercontent.com/20607348/127740052-c28cec74-d806-4601-b99d-2018c43fc818.png)

![image](https://user-images.githubusercontent.com/20607348/127740209-6b945c87-9b3f-46f7-b21e-4ee2386b316b.png)

readpixel is less than -1

Operating system: (please complete the following information)

- OS: win-64
- Version: Windows 10

**Comment by LovelySanta** [comment]
Can you reproduce this issue?

**Comment by realjf** [comment]
I saw the solution [#419](https://github.com/TheCherno/Hazel/pull/419) , and found the reason, thank you
