### ISSUE TITLE
Crash when I run HazelInput or Sandbox using VS2017.

### ISSUE THREAD

**Issue by liubinguo** [TheCherno/Hazel#473]
Crash when I run HazelInput or Sandbox using VS2017.
More infomations.
![image](https://user-images.githubusercontent.com/24774343/129046156-f84d5777-863a-4282-acfe-cadace7bd783.png)
![image](https://user-images.githubusercontent.com/24774343/129046257-60c33023-9109-4459-ac64-ad6a3711b6c7.png)

Any help will be greatly appreciated.

**Comment by IshoAntar** [comment]
I can't read Chinese but it's probably the same problem as #133 judging by the `0x00` addresses.

What's the output from the console?
