### ISSUE TITLE
..gitmodule issues

### ISSUE THREAD

**Issue by TnVolsFan82** [TheCherno/Hazel#477]
Gettin an error trying to get .gitmodule into my project/

C:\DEV2\Hazel>git submodule add https://github.com/TheCherno/Hazel Hazel/vendor/spdlog.git
fatal: please make sure that the .gitmodules file is in the working tree

**Comment by LovelySanta** [comment]
Is this your code along? In that case you need to use
```
git submodule add https://github.com/gabime/spdlog.git Hazel/vendor/
```
which corresponds to `git submodule [--quiet] add [<options>] [--] <repository> [<path>]`. For more documentation, see [the docs](https://git-scm.com/docs/git-submodule).

If you're cloning the Hazel repository, you must clone it as
```
git clone --recursive https://github.com/TheCherno/Hazel
```
I assume you cloned it incorrectly, to fix this, you have to init the submodules as follows
```
git submodule update --init
```
which is documented on our [readme](https://github.com/TheCherno/Hazel#getting-started).

For further questions, plz ask them in our discord. Closing this as a question.
