### ISSUE TITLE
Imgui fails to link into projects developed using hazel api

### ISSUE THREAD

**Issue by harshit2608** [TheCherno/Hazel#507]
#### Describe the bug
Imgui throws error when Hazelnut is build, as there seem to be some linking issue.

![image](https://user-images.githubusercontent.com/42277796/140973943-9077d37a-045b-455d-95c1-e676ebf52098.png)

#### To Reproduce
1. Just clone the repo
2. Build the project
3. Run the project
4. ERROR!!

**Comment by VagueLobster** [comment]
Hi there, i cannot reproduce the error, would you mind asking a few questions?

1) Are you trying to run the master branch? Because it runs fine for me.
2) Have you git clone --recursive or just downloaded the zip from github?
3) Have you run the setup.bat inside the Hazel/scripts/ folder?
4) Do you have an AMD GPU or Nvidia or possibly even Intel?

Thanks in advance for your time.

**Comment by harshit2608** [comment]
Hey there

1. Yes i am trying to run the master branch.
2. I have cloned recursively.
3. Yes i have ran the setup.bat inside Hazel/scripts/ folder
4. I have Nvidia GPU.

And i tried again but error continues.
Debug build : ❌ 
Release build : ❌ 
Dist build : ❌

**Comment by VagueLobster** [comment]
That sounds really strange, i am at a loss then :(

**Comment by harshit2608** [comment]
Hey there, i think i found the bug , its probably my system fault.
I cloned the repo and various other projects using imgui into my other system and they are working fine but on my system anything that uses imgui is failing to link.
Since i don't have any other project using imgui and cmake i was not able to confirm if Visual Studio 2019 is also responsible for generating the error.
Their might be a file in my system of imgui (imgui.lib) or something else which is giving error when linking imgui to projects.
But i don't know where it is,

Please help me resolve this issue.

**Comment by harshit2608** [comment]
I found the solution seems like i have imgui installed through vcpkg and hazel is linking to it.

**Comment by zejunli** [comment]
> I found the solution seems like i have imgui installed through vcpkg and hazel is linking to it.

Just spent the entire day on the same linking error but couldn't find why, just removed the imgui from my vcpkg and it's all good now, thanks!
