### ISSUE TITLE
Layers shall have mutex

### ISSUE THREAD

**Issue by Lecrapouille** [TheCherno/Hazel#523]
You cannot iterate on the stack of layers for updating while pushing/popping layer at the same time. Add mutex to make operation atomic

**Comment by cugone** [comment]
Adding a mutex/atomic operation won't fix the problem. As you describe it, pushing/popping from a vector iterates all iterators after the deletion/insertion. This is a known idiom in C++ and not related to mutexes or atomic operations.

**Comment by Lecrapouille** [comment]
@cugone You are so right :) The correct fix would be to have two containers. The 1st for iterating for the setup and paint actions. Modify the interface to push/pop/add/remove layers on the second containers. And before calling setup and paint method transfer layers from the 2nd container to the 1st.

**Comment by LovelySanta** [comment]
Closing this a question with an answer
