### ISSUE TITLE
Imgui linking problems

### ISSUE THREAD

**Issue by gabrielevierti** [TheCherno/Hazel#53]
I'm having some issues with linking Imgui to the "Sandbox" project lately;

I'm linking the IMGUI static library to the "Core" dynamic library (that gets linked into the sandbox project). 

I have decommented the "IMGUI_API" preprocessor for dllexport() inside imgui_config.h, but i still get an unresolved external:

    Severity	Code	Description	Project	File	Line	Suppression State 
    Error	LNK2019	unresolved external symbol "void __cdecl ImGui::ShowDemoWindow(bool *)" 
    (?ShowDemoWindow@ImGui@@YAXPEA_N@Z) referenced in function "public: virtual void 
    __cdecl Test::OnImguiRender(void)" (?OnImguiRender@Test@@UEAAXXZ)	Sandbox	 
    C:\Users\gabri\Documents\GitHub\Liquid-Engine\Sandbox\main.obj	1	

Here is my main.cpp:

    #include "Liquid.h"

    #include "..\..\IMGUI\src\imgui.h"

    class Test : public Liquid::Layer
    {
	public:

	void OnImguiRender() override
	{
		static bool show = true;
		ImGui::ShowDemoWindow(&show);
	}
    };

    class Sandbox : public Liquid::Application
    {
	public:

	Sandbox() : Liquid::Application("Game",960,540)
	{
		PushLayer(new Test());
	}

	~Sandbox()
	{	

	}
    };

    Liquid::Application* Liquid::CreateApplication()
    {
	return new Sandbox();
    }

Any kind of help is welcome, thanks a lot guys :)

**Comment by BlackWolf9584** [comment]
I am also getting LINK 2019 errors causing a LINK 1120 error for 25 unresolved externals all relating to ImGui

**Comment by TobiGamer** [comment]
I had the same problem, then I noticed something went wrong with the "ImGuiBuild.cpp" file.
It somehow was created outside the project. Simply deleting the file, and creating it new, completely solved the problem for me.

**Comment by phuachuzang** [comment]
I have an issue whereby when I try to compile "ImGuiBuild.cpp", it gives me alot of errors stating about IMGUI redefinitions. I've experimented and noticed that when I include the docking branch files, I cant seem to compile the files outside of the project like you did. 

I've been following the guide closely but not using premake.

**Comment by WhoseTheNerd** [comment]
This issue should be closed as this is not a problem for a Hazel code. If you need help with your own code ask it in [TheCherno's Discord Server](https://discordapp.com/invite/K2eSyQA)

**Comment by LovelySanta** [comment]
TobiGamer gave a solution for this, since this isn't an actual bug on Hazel, we're static linking and like WhoseTheNerd said, own issues should be placed on the discord.
Closing this as not part of Hazel & Resolved
