### ISSUE TITLE
ImGUI layer (a question

### ISSUE THREAD

**Issue by spaltiel** [TheCherno/Hazel#55]
Hi,

Why you have decided to include dear ImGUI layer inside your engine. It is a little weird to me since I believe that each game will have its on GUI. 

BTW very nice series!

10x!
A.I.

**Comment by Xiao-Houzi** [comment]
ImGUI  has been added as a debug and tools interface.

**Comment by spaltiel** [comment]
I thought that tools interface are also per game. What do I miss?

**Comment by Xiao-Houzi** [comment]
why would you reinvent the wheel each time you want to make a game? you'd definitely create a library, and if you're just gonna use one library for all, why not use one that's been made for you.
save your strength for creating a great game.

**Comment by spaltiel** [comment]
> why would you reinvent the wheel each time you want to make a game? you'd definitely create a library, and if you're just gonna use one library for all, why not use one that's been made for you.
> save your strength for creating a great game.

Generally I agree. 
However, in the current design ImGuiLayer::OnUpdate() includes all the actual GUI items.  In my opinion a better way is to exclude actual GUI items from the engine, it should be determine from outside of the engine so you can determine how the GUI will be looks like regardless of the engine which should be common for all games is as you wrote.
