### ISSUE TITLE
VulkanSDK-1.3.-Installer.exe Unsupported 16-bit Application

### ISSUE THREAD

**Issue by silvertakana** [TheCherno/Hazel#558]
#### Describe the bug
when trying to run Setup.bat and install Vulkan, it did not work.
![image](https://user-images.githubusercontent.com/62156548/175756471-9ac3fda0-af06-411c-a18e-5c3c36757eaf.png)
```
You don't have the Vulkan SDK installed!
Would you like to install VulkanSDK 1.3.? [Y/N]: y
Downloading https://sdk.lunarg.com/sdk/download/1.3./windows/VulkanSDK-1.3.-Installer.exe to ./Hazel/vendor/VulkanSDK/VulkanSDK-1.3.-Installer.exe
[██████████████████████████████████████████████████] 100.00% (89.97 KB/s)
Running Vulkan SDK installer...
Traceback (most recent call last):
  File "C:\Users\titmi\OneDrive\Desktop\Hazel\scripts\Setup.py", line 16, in <module>
    VulkanRequirements.Validate()
  File "C:\Users\titmi\OneDrive\Desktop\Hazel\scripts\SetupVulkan.py", line 17, in Validate
    if (not cls.CheckVulkanSDK()):
  File "C:\Users\titmi\OneDrive\Desktop\Hazel\scripts\SetupVulkan.py", line 31, in CheckVulkanSDK
    cls.__InstallVulkanSDK()
  File "C:\Users\titmi\OneDrive\Desktop\Hazel\scripts\SetupVulkan.py", line 58, in __InstallVulkanSDK
    os.startfile(os.path.abspath(vulkanPath))
OSError: [WinError 216] This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher: 'C:\\Users\\titmi\\OneDrive\\Desktop\\Hazel\\Hazel\\vendor\\VulkanSDK\\VulkanSDK-1.3.-Installer.exe'
```
![image](https://user-images.githubusercontent.com/62156548/175756556-162d9616-2c65-4a1d-af73-f643e91e04fa.png)

#### To Reproduce
1. make sure your machine doesn't have Vulkan installed
2. Go to 'scripts/'
3. Click on 'Setup.py'
4. Enter 'y' if ask to install vulkan
5. See error above

#### Operating system:
- OS: win-64
- Version: windows 11 pro

**Comment by Sebanisu** [comment]
I am having the same issue with the batch file. I used to work when we were using an older version of vulkan.

**Comment by Sebanisu** [comment]
He fixed this in the stream 5fda78b502be6692a90749620d673b606e013731

**Comment by TheZitroX** [comment]
Still doesn't work and the same popup for me

**Comment by TheZitroX** [comment]
After manual installation it worked fine
