### ISSUE TITLE
Documentation: Hazel is not on Wikipedia!

### ISSUE THREAD

**Issue by bren007pie** [TheCherno/Hazel#568]
#### Is your feature request related to a problem? Please describe
I did not see Hazel on the Wikipedia list of [game engines](https://en.wikipedia.org/wiki/List_of_game_engines). I believe this is because it also doesn't have a Wikipedia page. Adding a Wikipedia page would help solidify Hazel as an available game engine and might draw more interest to the project!

#### Describe the solution you'd like
1. Add a Wikipedia page for hazel
2. Edit the list of [gam eengines](https://en.wikipedia.org/wiki/List_of_game_engines) to add Hazel

#### Describe alternatives you've considered
This may need to wait until Hazel is more developed as an engine. 
Alternatively, it could not be added if it's not seen as that important.

#### Additional context
N/A

**Comment by darkvergus** [comment]
Not trying to be a jerk, but I think this is kinda pointless. The point of Hazel 2D is to be a learning course.

**Comment by AnantTiwari-Naman** [comment]
According to Wikipedia guidelines, I think you generally are not supposed to make articles on your work or yourself
