### ISSUE TITLE
One or more Projects in the solution were not loaded correctly

### ISSUE THREAD

**Issue by ALALACH** [TheCherno/Hazel#58]
Hello peeps!
i tried running the .sln on Virtual Studio 19 and ended up with the error below.
i figured changing to VS17 would solve this (probably due to some linkage/version issues) but it wasnt the case.
Hazel folder was both manually extracted / git cloned / git submoduled and same for all the external vendor dependencies.
the GLFW / Imgui are the unloaded solutions and there is no .sln file inside their repositories
(cherno mentioned stuffs about Glad being added instead of forked and submodeled and its loading properly : maybe thats something there but im missing the hint)
anyhow heres the error message (Cmake?)

Severity	Code	Description	Project	File	Line	Suppression State
Error		CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
VULKAN_LIBRARY (ADVANCED)		C:\dev\Hazel-master\Hazel\vendor\imgui\examples\example_glfw_vulkan\Please set them or make sure they are set and tested correctly in the CMake files

**Comment by ALALACH** [comment]
C:\dev\Hazel-master\Hazel\vendor\imgui\ImGui.vcxproj : error  : The project file could not be loaded. Could not find file 'C:\dev\Hazel-master\Hazel\vendor\imgui\ImGui.vcxproj'.  C:\dev\Hazel-master\Hazel\vendor\imgui\ImGui.vcxproj

**Comment by ALALACH** [comment]
Solved.
i had some issues configuring the premake file.
followed litterally the instruction on the premake episode.

**Comment by WhoseTheNerd** [comment]
If this is solved, please close it.
