### ISSUE TITLE
QOL optimizations

### ISSUE THREAD

**Issue by scriptSQD** [TheCherno/Hazel#586]
Is it really necessary to have all that switch cases:
https://github.com/TheCherno/Hazel/blob/49da3c1e08245feb5b978269119f50b0873dc9d1/Sandbox/assets/shaders/Texture.glsl#L65-L96

When you can simply do:
```glsl
texColor *= texture(u_Textures[int(Input.TexIndex)], Input.TexCoord * Input.TilingFactor);
```

I might be wrong because I haven't especially tested it (I'm on Linux without access to Windows machine rn).
I see you might need some kind of check to be sure that TexIndex is in bounds of [0...31], but that's just one if-statement which is much cleaner than 32 line of code basically picking the right texture index.

**Comment by DrOptix** [comment]
Check: https://github.com/TheCherno/Hazel/issues/238

**Comment by scriptSQD** [comment]
Makes sense, stumbled upon this while messing with my shaders.
