### ISSUE TITLE
 Software & game dev is easy and for kids, and has absolutely nothing to do with a real and serious complex subject like engineering.

### ISSUE THREAD

**Issue by ghost** [TheCherno/Hazel#589]
This post is in response to the pathetic & disrespectful lies which use  falsely use the word "Engineering", which makes absolutely no sense (and is disrespectful to real Engineering). 

Software devs are stupid wannabe kiddos who keep making huge fake claims. 
Engineering has nothing to do with sitting behind a keyboard and writing code.@TheCherno   There is no such thing as "software" "engineering". Engineering is a real subject. Engineering means designing and building real mechanical systems, like vehicular engines and turbojets.

Software devs are claiming the most ridiculous of false claims these days. Software & game dev is easy and for kids, and has absolutely nothing to do with a real and serious complex subject like engineering. Stop being disrespectful to Engineering. And stop these stupid lies.

Mechanical Engineering is the only Engineering. Period.

**Comment by CheerWizard** [comment]
@ghost "Software & game dev is easy and for kids" - are you kidding dude? 
First of all, It tooks a lot of time to develop software properly and development is not only writing a code. You can separate it in different stages like : 
- planning design
- coding
- testing
- measuring
- repeating and review
- releasing
