### ISSUE TITLE
forking issues

### ISSUE THREAD

**Issue by ALALACH** [TheCherno/Hazel#59]
well im by no mean a git expert but forking the project from an updated repository gives me an outdated version of it (on my local repository) and i dont seem to figure out how to fix that.
anyone here who have been through the same issue can fix ?

**Comment by rjgp** [comment]
Once you have forked a repo, you should keep it up to date: [https://help.github.com/en/articles/syncing-a-fork](https://help.github.com/en/articles/syncing-a-fork)

**Comment by Gaztin** [comment]
Closing because it looks to be resolved. Please open again if that is not the case.
