### ISSUE TITLE
Mac OS X support

### ISSUE THREAD

**Issue by GabrieleInvernizzi** [TheCherno/Hazel#6]
How can I use the code in Xcode on Mac? If there is a way of course

**Comment by S-Marais** [comment]
following today's video you should be able to create a an xcode solution. you will need to get premake5 binaries from github and the launch `premake5 xcode4` which should generate the xcode project files

**Comment by gabrielevierti** [comment]
you should also be adding macros like *HZ_PLATFORM_MACOS*

**Comment by lccatala** [comment]
also, __declspec(dllexport) and __declspec(dllimport) seem to be Windows-exclusive. I've been looking for an alternative way of exporting and importing symbols on Mac but can't seem to find anything. Is this supposed to work without defining anything?

**Comment by S-Marais** [comment]
no the std like alternative is
```cpp
#define HAZEL_API __attribute__((visibility("default")))
```

**Comment by lccatala** [comment]
Ok, so I managed to build and run the Sandbox project, however when I click
on Xcode's play button with that project selected, it says "Build
Succeeded" and nothing happens. Shouldn't a terminal window open?

**Comment by Ali-Shery** [comment]
No it would be using the built in terminal in Xcode. Just change the setting to launch new terminal on application run in Xcode.

**Comment by GabrieleInver** [comment]
Iccatala, sorry, can you explain me how did you managed to build this project on xCode, I tried but I can’t do it ahah

**Comment by lccatala** [comment]
You have to create a new filter for "system:macosx" using the same
configurations as for the Windows one, replacing every "windows" word for
"mac", so the code you compile is different for each platform. In Core.h,
remove the #error macro (there is no need for __declspec(dllexport) in
xcode, since every class and function will be accesible throughout the
whole solution by default). Then download and install premake for mac and
run it with the parameter xcode4. Let me know if there are any errors
remaining, it's possible I've forgotten something.
Also, I'll try to build it for cmake so it can be edited from VSCode, which
I think is far superior to XCode

**Comment by GabrieleInver** [comment]
Thank you very much, I'll try

**Comment by GabrieleInver** [comment]
I tried but it doesn't work, perhaps is my fault but can you help me with this?
This is my premake5.lua file (I know that this is a txt but GitHub do not support .lua):
[premake5.txt](https://github.com/TheCherno/Hazel/files/2644959/premake5.txt).

I think I did some (if not a lot) mistakes, can you help me?

**Comment by cubedtear** [comment]
On PR #27 we have a working build on Linux, which should contain similar changes to those needed for Mac OS X support. You could maybe try those changes (maybe changing all the `system:linux` with `system:macosx`) to see if it works.

**Comment by not-a-vegetable** [comment]
@GabrieleInvernizzi  How about you Use clion (an ide that uses cmake) instead of premake and xcode .. spglog and glfw already use cmake and writing cmake files for glad and imgui wont be hard. I just like that clion is cross platfrom and i can work from my macbook or windows pc. https://www.jetbrains.com/clion/

**Comment by SUNYPoly-Steven** [comment]
@not-a-vegetable you can generate cmake files with premake. If you want to use clion you can do that here's the link to the extension

https://github.com/TurkeyMan/premake-cmake

**Comment by mfdorst** [comment]
@thatweirdcoder I also enjoy CLion for the same reason. However for those who prefer Xcode, it also supports CMake, so there's no reason you have to switch to a new IDE to use it.

**Comment by cxgslegend** [comment]
> @not-a-vegetable you can generate cmake files with premake. If you want to use clion you can do that here's the link to the extension
> 
> https://github.com/TurkeyMan/premake-cmake

Unfortunately, it doesn't work with premake5, and the creator isn't updating the project. [Issue from 2015](https://github.com/TurkeyMan/premake-cmake/issues/1). It seems like there are no cmake action extensions. Even the one listed in the premake docs is dead [Premake modules](https://github.com/premake/premake-core/wiki/Modules).

**Comment by jviney** [comment]
If anyone is interested, I'm doing this series on macOS using VS Code with CMake instead of premake.

I'm currently up to episode 16. Works fine with Xcode if you want to use that.

https://github.com/jviney/hazel

**Comment by cxgslegend** [comment]
> If anyone is interested, I'm doing this series on macOS using VS Code with CMake instead of premake.
> 
> I'm currently up to episode 16. Works fine with Xcode if you want to use that.
> 
> https://github.com/jviney/hazel

I assume you are talking about a youtube series. You should probably not promote Hazel issues. This would be more appropriate for the "game engine series" section in discord.

But regardless, you do not have a link on your github project to the series.

**Comment by tcaer** [comment]
Hi, 
I am on MacOS and I have built an engine which is basically Hazel but works on both MacOS and Windows. For Hazel's premake5 file, I added this:
```
filter "system:macosx"
    defines {
      "CFG_MACOS",
      "__APPLE__"
    }
    kind "SharedLib"

    links {
      "OpenGL.framework",
      "Cocoa.framework",
      "OpenGL.framework",
      "IOKit.framework",
      "CoreFoundation.framework"
    }
```
configuration to it. I then also added this to the GLFW configuration:
```
filter "system:macosx"
    systemversion "latest"
    staticruntime "On"
    
    files {
      "src/cocoa_init.m",
      "src/cocoa_joystick.m",
      "src/cocoa_monitor.m",
      "src/cocoa_time.c",
      "src/posix_thread.c",
      "src/cocoa_window.m",
      "src/egl_context.c",
      "src/nsgl_context.m",
      "src/osmesa_context.c"
    }

    defines {
      "_GLFW_COCOA"
    }
```
My version of the engine does not require any of the DLL_EXPORT/IMPORT stuff in it. But these settings will build GLFW properly for MacOS.

**Comment by tcaer** [comment]
Furthermore, the `"GLFW_INCLUDE_NONE"` macro has to be moved to be a windows-only macro. MacOS requires us to use `glfwWindowHints` to set the proper context version. Also, the engine has to support version 410 as that is the highest version MacOS supports. 
```
glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
```
This code is required in a Mac window to ensure that the core profile and GL version 410 is being used.

**Comment by SteveGremory** [comment]
how about just creating a different repo for macOS and linking it in this one?

**Comment by i-bajrai** [comment]
Ugh zombie thread but I was able to get @jviney 's version running in 2025 with some finessing, I'm a PHP developer so this is extremely exciting to actually get running on my machine, maybe someone has created a better version of this now but it does still work!

<img width="1296" height="762" alt="Image" src="https://github.com/user-attachments/assets/d0787e5c-1e50-4c48-8666-fbc247b027e2" />
