### ISSUE TITLE
sandbox not working while debugging in mvs

### ISSUE THREAD

**Issue by Ahmed-elshorbagy** [TheCherno/Hazel#60]
when i build the project it builds successfully but when i try to run it in the debugger it gives me this error while it doesn't give any error while running outside mvs
i tried to add the debugger and mvs to work on nividia card but nothing happened
this is the error message:

> THE Engine
[21:47:53] HAZEL: Initialized Log!
[21:47:53] APP: Hello
[21:47:53] HAZEL: Creating Window Hazel Engine (1280,700)
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile vertex shader!
ERROR: 0:1: '' :  Version number not supported by OGL driver
ERROR: 1:1: 'layout' : syntax error syntax error
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader!
ERROR: 0:1: '' :  Version number not supported by OGL driver
ERROR: 1:1: 'in' :  supported in GLSL 1.30 or later
ERROR: 1:2: 'in' :  supported in GLSL 1.30 or later
ERROR: 1:4: 'layout' : syntax error syntax error
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! (wi
th GLSL '#version 410
')

**Comment by BlackWolf9584** [comment]
@Ahmed-elshorbagy what do your shaders look like as that looks like the issue is with the code that handles them

**Comment by Gaztin** [comment]
I think something might have gone wrong when checking out the ImGui submodule. @ritobanrc had the same issue in #27 and they resolved it by re-cloning the project.
