### ISSUE TITLE
Hazel/src/Platform/OpenGL/OpenGLShader.cpp at line 19, glTextureParameteri()

### ISSUE THREAD

**Issue by yaseenshaikh96** [TheCherno/Hazel#602]
#### Describe the bug

```
glTextureParameteri(m_RendererID, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
```
Should be

```
glTextureParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
```

[Link to docs.gl page.](https://docs.gl/gl4/glTexParameter)

Shouldn't the function take a glenum as the texture is assumed to be binded first?

Sorry, I cannot run this on my machine to verity, as it doesn't support OpenGL 4.5.

**Comment by SeppahBaws** [comment]
> Shouldn't the function take a glenum as the texture is assumed to be binded first?

Nope, you're confusing two different functions with each other. On the docs page, note the difference between `glTexParameteri` and `glTextureParameteri`:
```
void glTexParameteri(GLenum target, GLenum pname, GLint param);
void glTextureParameteri(GLuint texture, GLenum pname, GLint param);
```

And down in the Notes section:
> `glTexParameter` specifies the texture parameters for the active texture unit, specified by calling `glActiveTexture`. `glTextureParameter` specifies the texture parameters for the texture object with ID texture.

**Comment by yaseenshaikh96** [comment]
yes i see it now. Thanks for the clarifications!
