### ISSUE TITLE
Hazelnut cannot find the correct dlls

### ISSUE THREAD

**Issue by szkristof32** [TheCherno/Hazel#613]
#### Describe the bug
I cloned and set Hazel up by following the instructions in the readme, then built it. I didn't get any errors (only warnings). But when I ran Hazelnut it said that the code execution cannot proceed because shaderc_sharedd.dll was not found. It was strange because shaderc links with a lib, and Hazel shouldn't be looking for dlls.

#### To Reproduce
I can't exactly describe how to reproduce this because I don't know anything about what causing this error.

#### Expected behavior
I would except Hazelnut to start and work properly.

#### Screenshots
The exact error message:
![error](https://user-images.githubusercontent.com/33003623/221025379-19fb8627-15f9-4650-bde4-826b69575d31.png)
The build output:
[Output-Build.txt](https://github.com/TheCherno/Hazel/files/10816669/Output-Build.txt)

#### Operating system: (please complete the following information)
- OS: win-64
- Version: Windows 11 Professional

#### Additional context
GPU Vendor: **NVIDIA**
GPU Driver Version: **528,49**
GPU Model: **NVIDIA GeForce RTX 2060**
Vulkan Version: **1.3.216.0**

**Comment by VagueLobster** [comment]
> 

You need to install VulkanSDK, if you don't have VulkanSDK installed Hazel can't find the SPIR-V related dll's!
When you have installed VulkanSDK, you need to go into Hazel/scripts/ and run Setup.bat!
You also need an system variable called VULKAN_SDK with the path:
C:\VulkanSDK\1.3.216.0
NOTE! you need VulkanSDK version 1.3.216.0 (i don't think you can run newer or earlier versions yet!) in order to run Hazel successfully.
If you don't do these things, you can't run Hazel...

**Comment by VagueLobster** [comment]
>It was strange because shaderc links with a lib, and Hazel shouldn't be looking for dlls.
This statement is not entirely correct!
Hazel looks for a *.lib file, yes, that's correct. But that *.lib uses the *.dll file!
And therefore, you need that *.dll to be in the C:\VulkanSDK\1.3.216.0\Bin folder in order to run VulkanSDK correctly.

**Comment by szkristof32** [comment]
Thank for the help.
I was able to track down the problem very easily after your reply. I had the Vulkan SDK installed and I had all the libs in the `Lib` folder and all the dlls in the `Bin` folder. Problem was, that I hadn't had this folder in my PATH variable. After I put that in, it worked fine.

**Comment by VagueLobster** [comment]
That's great to hear you got it working 😄
