### ISSUE TITLE
How to output pointers in spdlog

### ISSUE THREAD

**Issue by Lostness-Wf** [TheCherno/Hazel#621]
When I use "HZ_CORE_INFO"  to print GL_Vender or GL_Version,there is a staitc_assert failed
![屏幕截图 2023-04-08 224402](https://user-images.githubusercontent.com/109720649/230727644-787e861b-ff89-4fc7-ad6a-24e4813805de.png)
So I use fmt::ptr()
![屏幕截图 2023-04-08 224945](https://user-images.githubusercontent.com/109720649/230727695-3eed5a74-9c4d-41b1-9aa4-95807d8e97cd.png)
But what I got on the console was pointer address. What should I do?
![屏幕截图 2023-04-08 225226](https://user-images.githubusercontent.com/109720649/230727857-b0515203-e053-4b0a-a553-ad46e228f769.png)

**Comment by DenisGames** [comment]
You can cast the returned string to a c string and it should work
`HZ_CORE_INFO("Vendor: {0}", (const char*)glGetString(GL_VENDOR))`

**Comment by Lostness-Wf** [comment]
> You can cast the returned string to a c string and it should work `HZ_CORE_INFO("Vendor: {0}", (const char*)glGetString(GL_VENDOR))`

Thank you, it works
