### ISSUE TITLE
shaderc_sharedd.dll error

### ISSUE THREAD

**Issue by aadipoddar** [TheCherno/Hazel#626]
## DLL Error
A build of the hazel engine returns a DLL error

![image](https://github.com/TheCherno/Hazel/assets/83405769/ec83a7ce-5df1-464f-a0bd-d0d6a575d941)

**Comment by VagueLobster** [comment]
> ## DLL Error
> A build of the hazel engine returns a DLL error
> 
> ![image](https://user-images.githubusercontent.com/83405769/242683486-ec83a7ce-5df1-464f-a0bd-d0d6a575d941.png)

You need to install the Vulkan SDK... if you downloaded the master repo and not an old master, then you need to install at least Vulkan SDK version 1.3.216.0 if you're uising an older version of Vulkan SDK, then it won't work on the newest version of Hazel!
