### ISSUE TITLE
When running setup.bat file I get "Error: cannot open Hazel/vendor/msdf-atlas-gen: no such file or directory"

### ISSUE THREAD

**Issue by yetry504** [TheCherno/Hazel#629]
When running setup.bat file I get "Error: cannot open Hazel/vendor/msdf-atlas-gen: no such file or directory". But when I go to the specified path the folder msdf-atlas-gen does exist. 

1. Go to './scripts'
2. Click on 'setup.bat'

Expected behavior
setup to be able find msdf-atlas-gen as the folder does exist in the specified path and finish setup successfully

Result behavior
setup cannot open msdf-atlas-gen and says it does not exist even though it does

![image](https://github.com/TheCherno/Hazel/assets/137683514/ffde130d-29ba-4998-8126-5a8e33ce4e2f)

**Comment by iceonepiece** [comment]
In .gitmodules file. You should try change

> path = Hazel\\vendor\\msdf-atlas-gen

to

> path = Hazel/vendor/msdf-atlas-gen
