### ISSUE TITLE
Issue with premake

### ISSUE THREAD

**Issue by Kogularaj-K** [TheCherno/Hazel#63]
//cmd begins here...
F:\C++\VS2019\Solutions\GameEngine>call Dependencies\premake5\premake5.exe --file=PreGameEngine.lua vs2019
Error: [string "src/base/_foundation.lua"]:127: attempt to concatenate a table value (local 'fname')

F:\C++\VS2019\Solutions\GameEngine>pause
Press any key to continue . . .
//cmd ends here...

Hi Cherno! How should I clear this error? I'm using vs 2019 and premake 5 alpha 14..
Thanks in advance!

**Comment by lucaslohne** [comment]
Did you wrote in the lua file "includedirs" instead of "include"? He had the same error message in the video and also showed the correction. I also used vs 2019 and premake 5 alpha 14 and had no problems.

**Comment by Gaztin** [comment]
Closing this for now. Please reopen if this still is an issue after @lucaslohne's fix

**Comment by Lets-A-Code** [comment]
I also have this problem but it is like

C:\Dev\C++\GShell> vendor\bin\premake\premake5.exe vs2019
Error: [string "src/base/_foundation.lua"]:127: attempt to concatenate a table value (local 'fname')

// GShell is my own engine based on Hazel

**Comment by NCC1705** [comment]
The answer is at the end of the video. Worked for me in VS 202
![premake](https://user-images.githubusercontent.com/10720891/179755479-4804595f-0c93-4436-bf65-c7cb5ed06220.png)
2
