### ISSUE TITLE
Folder msdf-atlas-gen empty upon recursive clone

### ISSUE THREAD

**Issue by CardboardCartographer** [TheCherno/Hazel#631]
I just cloned the Hazel engine to use it, but the msdf-atlas-gen folder is empty, which crashes the setup.bat file.

**Comment by PCForrest** [comment]
This is a known issue (see [#617](https://github.com/TheCherno/Hazel/pull/617)).

To manually resolve the problem, edit the .gitmodules file (in the root folder) and replace all backslashes with forward slashes.
Re-run setup.bat to update the missing module.

**Comment by VagueLobster** [comment]
> could this please be fixed in the repo

You either have to be patient and wait until Cherno commits a fix, or you could just fix it yourself by literally changing the .dependencies file and change the \\ to / down at the msdf-atlas-gen part of the file 👍
