### ISSUE TITLE
D3D11 support

### ISSUE THREAD

**Issue by nathan130200** [TheCherno/Hazel#635]
The Hazel engine I've been following is very good and very interesting, especially being able to create components and scripts in C#.

Are there any future plans to support DirectX 11? It would be really interesting if Hazel could support DX11, as not all GPUs support Vulkan directly.

From what I could see in the code, vulkan was directly inserted in the rendering layer without any extra abstraction, which makes it difficult to modify it, having to change several parts hoping the code doesn't break.

**Comment by VagueLobster** [comment]
> Are there any future plans to support DirectX 11? It would be really interesting if Hazel could support DX11, as not all GPUs support Vulkan directly.

There's no future plans to support any DirectX version currently, as Cherno has said that he wants to support as many OSes as possible, and by having DirectX 11 / 12, that would kill that possibility! And Cherno has also already said, that he won't support multiple Graphics API's, so when we get to implement Vulkan, that will mean that we kill OpenGL support! Lastly, most GPU's these days support some kind of version of Vulkan, so it shouldn't be a problem anyway.

**Comment by nathan130200** [comment]
Yeah i'm with old GPU (GeForce 710M), and sadly it does not support any Vulkan version 😞

**Comment by nathan130200** [comment]
Yes, my GPU is really old (GeForce 710M) unfortunately it doesn't support Vulkan 😕

But anyway, thanks for the info!

**Comment by nathan130200** [comment]
Yes, my GPU is really old (GeForce 710M) unfortunately it doesn't support Vulkan 😕

But anyway, thanks for the info!
