### ISSUE TITLE
Hazelnut crashing when opening Sandbox.hproj

### ISSUE THREAD

**Issue by hellisabove** [TheCherno/Hazel#637]
#### Describe the bug
After compiling the project and hazelnut opening, selecting the sanbox project .hproj file, hazelnut crashes

Make sure your bug can be reproduced with the Hazel Engine and not by your own engine that you're creating alongside with Hazel. For issues with your own engine, we're happy to help you in [TheCherno Discord server](https://thecherno.com/discord). Thanks for your understanding.

#### To Reproduce
1. Open Hazel.sln
2. Click on Build Solution
3. Open Sandbox.hproj
4. See error above

#### Expected behavior
Hazelnut opening Sandbox.hproj withour problems as expected from ![the guide on hazelengine.com](https://docs.hazelengine.com/Welcome/GettingStarted)

#### Screenshots
If applicable, add extra screenshots to help explain your problem.
![Screenshot 2023-07-24 005247](https://github.com/TheCherno/Hazel/assets/59116609/d2bbc5bd-32c5-4a32-9d69-9906c7094bde)

#### Operating system: (please complete the following information)
- OS: win-64
- Version: Windows 10 Pro For Workstations

#### Additional context
It says something about not being able to load the app assembly of Hazel-ScriptCore

**Comment by VagueLobster** [comment]
You need to go into Hazel-Editor/SandboxProject/Assets/Scripts/ and generate the solution file with the Win-GenProjects.bat file, and the build the newly generated solution! Then Sandbox.hproj should work!

**Comment by hellisabove** [comment]
Now it does this
![Screenshot 2023-07-24 013233](https://github.com/TheCherno/Hazel/assets/59116609/6714ea48-b62a-44ea-921c-8812059271a6)

**Comment by VagueLobster** [comment]
What version are you running? Master branch or asset-manager branch?

**Comment by hellisabove** [comment]
Master

**Comment by VagueLobster** [comment]
Wait a minute! Have you edited the .gitmodules so you actually downloaded msdf-atlas-gen? And did you clone the repository recursively?

**Comment by hellisabove** [comment]
yes

**Comment by VagueLobster** [comment]
Okay hang on for a mniute or two, then i'll try and replicate the error :)

**Comment by VagueLobster** [comment]
That's extremely strange, because i did what you said to do above in the original meesage, and I can run little Hazel just fine :/
When exactly does that new error happen? I can't just use screenshots of the command prompt...

**Comment by hellisabove** [comment]
After building the project in visual studio 2022 i run with the local debugger, select sandbox.hproj and then the error happens

**Comment by hellisabove** [comment]
I can try recording and seting it up all over again if it helps

**Comment by VagueLobster** [comment]
Did you even go into Hazelnut/SandboxProject/Assets/Scripts/ and generate the solution file with the Win-GenProjects.bat file? and then built the newly generated solution? Because that really is important to do! Also I first wrote Hazel-Editor which was a typo, my bad!

**Comment by hellisabove** [comment]
Yes. I did that. Even cleaned the solution but it still doesn't work

**Comment by VagueLobster** [comment]
Okay, I have one last thing I want to ask you about... which GPU are you using?

**Comment by hellisabove** [comment]
At how armoury crate is configured it is in MSHybrid mode

**Comment by VagueLobster** [comment]
> At how armoury crate is configured it is in MSHybrid mode

Maybe that's the problem then... Idk what Armoury crate is, but it sounds like a company?

**Comment by hellisabove** [comment]
It's a management app for ROG laptops

**Comment by hellisabove** [comment]
I switched to dGPU only and will try again to see the results

**Comment by VagueLobster** [comment]
Great lemme know what the result is :)

**Comment by hellisabove** [comment]
From what I found online the problem comes from some issue with my amd drivers.

**Comment by VagueLobster** [comment]
Oh you have AMD, then yeah that can be a problem, though Yan did make the shaders support AMD GPUs, but maybe it's something else with AMD... Are you up-to-date with the drivers? and how old is the GPU? These two questions are really important.

**Comment by hellisabove** [comment]
Well at the moment I'm reinstalling the drivers. For how old i don't know. It is integrated. All I know is the apu is a ryzen 7 4800hs with renoir graphics or vega 7. For the discrete GPU it is a nvidia geforce gtx 1650

**Comment by VagueLobster** [comment]
Thanks! Do you have the ability to disable the apu through software? Because it really shouldn't be enabled when you have a far better discrete GPU!

**Comment by VagueLobster** [comment]
Also, have you updated the NVidia drivers as well?

**Comment by hellisabove** [comment]
For the nvidia drivers I looked and did an update to the driver from a few days ago. For the amd drivers they are almost done. I will update after they are done to see if anything changed

**Comment by VagueLobster** [comment]
Okay, then the NVidia drivers shouldn't be the problem 🙂

**Comment by hellisabove** [comment]
I have updated everything, made windows use only dGPU and now Hazelnut compiles without errors and I can use it perfectly. Thanks for helping me!

**Comment by VagueLobster** [comment]
> I have updated everything, made windows use only dGPU and now Hazelnut compiles without errors and I can use it perfectly. Thanks for helping me!

My pleasure 😄
