### ISSUE TITLE
EventSystem Compileerror: use of undefined type 'std::basic_ostream<char,std::char_traits<char>>

### ISSUE THREAD

**Issue by TerraCraftere3** [TheCherno/Hazel#638]
### Bug when compiling
Hey, i get an error everytime i try compiling my gameengine, i am currently working on my first gameengine and watching the "GameEngine Series" and trying to get the eventsystem running, it says _**use of undefined type 'std::basic_ostream<char,std::char_traits<char>>'**_ and things like **_'iostate': undeclared identifier_**, i have a github repo called [TerraCraftere3/Titan](https://github.com/TerraCraftere3/Titan/tree/eventsystem) on the branch eventsystem.
![errorlist](https://github.com/TheCherno/Hazel/assets/108687928/d71850f2-1464-49cd-8868-62cf0baa07d7)

**Comment by TerraCraftere3** [comment]
Also when i compile the engine it gives me no errors, but when i compile Sandbox it gives me all this errors

**Comment by VagueLobster** [comment]
> Also when i compile the engine it gives me no errors, but when i compile Sandbox it gives me all this errors

You're better off asking in Cherno's Discord Server ;) You're asking for help regarding your _**own**_ engine, and _**not**_ little Hazel!

**Comment by TerraCraftere3** [comment]
ok, thank you @VagueLobster
