### ISSUE TITLE
Win-GenProjects.bat can't find msdf-atlas-gen

### ISSUE THREAD

**Issue by ShaiAvr** [TheCherno/Hazel#646]
#### Describe the bug
I'm trying to use the Hazel engine for the first time. I ran `git clone --recursive https://github.com/TheCherno/Hazel` as instructed and installed the Vulkan SDK. I then ran the `Setup.bat` file. It detected Python, premake, and Vulkan correctly but failed to run premake with an error: `Error: cannot open Hazel/vendor/msdf-atlas-gen: No such file or directory`.

Running `Win-GenProjects.bat` gives the same error and it doesn't matter whether I run it from a terminal or from the file explorer:

![Screenshot 2023-09-29 113825](https://github.com/TheCherno/Hazel/assets/35605235/3ec01c1a-bee6-4196-8ae5-a2b542ba1fa2)

#### To Reproduce
1. Clone a fresh install of thee repository as instructed in the `README` file.
2. Download the Vulkan SDK as instructed.
3. Run `Setup.bat` and get the this error.
4. The same error occurs for `Win-GenProjects.bat`.

#### Expected behavior
The setup should work and generate a Visual Studio solution.

#### Operating system: (please complete the following information)
- OS: win-64
- Version: Windows 11 Pro

**Comment by Kirdow** [comment]
Known issue (See #617), you could also follow the temporary fix mentioned by PCForrest in #631.
