### ISSUE TITLE
Hazel/vendor/msdf-atlas-gen doesn't exist?

### ISSUE THREAD

**Issue by kaitabuchi314** [TheCherno/Hazel#649]
It says can't open: Hazel/vendor/msdf-atlas-gen. It doesn't even exist!

**Comment by VagueLobster** [comment]
> It says can't open: Hazel/vendor/msdf-atlas-gen. It doesn't even exist!

In the .gitmodules you need to change the \ to / in the msdf-gen-atlas
It's also been made as a pull request already in: https://github.com/TheCherno/Hazel/pull/617
