### ISSUE TITLE
Use zig as compiler instead of clang

### ISSUE THREAD

**Issue by PhilippWendel** [TheCherno/Hazel#650]
## What is zig?
Zig is a general-purpose programming language and **toolchain for maintaining robust, optimal and reusable software**.
It's really three things:
- ~~Programming language~~ Not important for hazel
- Build system (build.zig) replacing makefiles/cmake/ninja/etc
- C/C++ compiler with an emphasis on cross-compilation

# Why use zig over clang?
These 2 blog posts describe the reasons better than i could, but heres a tldr:
- **cross-compilation from any major os+isa to any major os+isa**
- **small archive (~45mb on linux) with single static executable under mit license, that ships with common libraries like libc, libcxx, compiler-rt, tsan, libunwind**
- builtin caching
- [package manager](https://devlog.hexops.com/2023/mach-ecosystem-c-libraries/#zig-has-a-new-package-manager-for-cc-too)
- better defaults (enables UBSAN, uses all supported cpu features, e.g. SSE or AVX)
- drop-in replacement

Guide on setting up zig as c/c++ compiler
- [Compile a C/C++ Project with Zig](https://zig.news/kristoff/compile-a-c-c-project-with-zig-368j)

Overview of the main features of zig as c/c++ compiler
- [`zig cc`: a Powerful Drop-In Replacement for GCC/Clang](https://andrewkelley.me/post/zig-cc-powerful-drop-in-replacement-gcc-clang.html)

# Links and further reading
Official website
- https://ziglang.org

Examples
- [Example of small project using zig as compiler and toolchain](https://github.com/jedisct1/minisign)
- [Example of larger project using zig as compiler and toolchain](https://github.com/andrewrk/ffmpeg)

**Comment by Kirdow** [comment]
I thought Hazel mainly uses MSBuild/MSVC and not Clang. How would you integrate this into Visual Studio?

**Comment by PhilippWendel** [comment]
@Kirdow
> I thought Hazel mainly uses MSBuild/MSVC and not Clang. How would you integrate this into Visual Studio?

I came here after chernos lastest video [Hazel Engine ON LINUX!](https://www.youtube.com/watch?v=I4TQI7st0pc). The new linux builds use clang.

Using zig would drop the need for extra linux ci/cd or simplify it greatly since there would be only one runner using zig compiling for all platforms and not one runner for each platform. Or you compile for linux on windows.

**Comment by Kirdow** [comment]
That video you linked is for Hazel 3D/Big Hazel. Not Hazel 2D/Game Engine series which this repository is about. The repository you're after is [under StudioCherno](https://github.com/StudioCherno/Hazel) which is available to Patrons.

**Comment by PhilippWendel** [comment]
> That video you linked is for Hazel 3D/Big Hazel. Not Hazel 2D/Game Engine series which this repository is about. The repository you're after is [under StudioCherno](https://github.com/StudioCherno/Hazel) which is available to Patrons.

Ok, sorry my bad. I'll close the issue then.
