### ISSUE TITLE
Unable to save a new Scene - "The file name is not valid" 

### ISSUE THREAD

**Issue by Atijaf** [TheCherno/Hazel#656]
When creating a new project and trying to save the scene, I receive a prompt stating "The file name is not valid" and the scene does not save.

1. Clone repo per [Getting Started](https://docs.hazelengine.com/Welcome/GettingStarted)
2. Create a New Project ( I created mine in a different folder than Hazel )
3. Click Save Scene As..  Navigate to New Project / Assets / Scenes
4. Try saving the scene as "TestScene" 

#### Expected behavior
A new scene should be saved in the folder.

![Hazel Screenshot](https://github.com/TheCherno/Hazel/assets/7007335/c409b858-9a10-4462-a834-e399abcbc504)

- OS: Win-64
- Version: Windows 10 home

I am eventually able to save the scene if I follow these steps in this order
1: Name the save "TestScene*.hscene"  - and try saving (Nothing happens)
2: Name the save "TestScene.hscene" - and save

**Comment by VagueLobster** [comment]
Are you by any chance trying to save a new scene inside of Hazel Dev? 'Cause this is the repo for Hazel 2D, which does not have *.hscene! It uses the *.hazel filetype for it's scenes! Also the link you provided for the getting started insinuates that you do in fact tried to get started with Hazel Dev...
