### ISSUE TITLE
Error on the first compiling of Hazel.sln

### ISSUE THREAD

**Issue by alebruna** [TheCherno/Hazel#661]
I recursively downloaded the hazel repository as instructed and then tried to run Setup.bat and it says:

Python version 3.12.0 detected.
Correct Premake located at C:\..\Hazel\vendor\premake\bin

Located Vulkan SDK at C:\..\VulkanSDK
You don't have the correct Vulkan SDK version! (Engine requires 1.3.) 

but I have installed on my PC the latest version of VulkanSDK (1.3.275.0). So I don't install Vulkan a second time. The setup concludes correctly but when i try to compile the Hazel.sln there are two errors. 

1)
Visual studio can't open: '..\..\VulkanSDK\Lib\shaderc_sharedd.lib'
but when i check the Vulkan directory the library is present with a slightly different name.

 2)
Visual studio can't open: '..\Hazel\bin\Debug-windows-x86_64\Hazel\Hazel.lib'
Inside '..\bin\Debug-windows-x86_64\Hazel\' there are two other files but 'Hazel.lib' is missing

**Comment by VagueLobster** [comment]
I have just downloaded Vulkan SDK 1.3.275.0 and Hazel's master repo, and it works for me so i'm thinking that you unticked the "install Vulkan debug symbols for x64" and that optional install is actually required for you too have the debug libs on your pc for the SDK.
