### ISSUE TITLE
I have added the transform component UI to my Engine and it's working good but there is a slight problem .

### ISSUE THREAD

**Issue by FlyingStudent** [TheCherno/Hazel#670]
#### Describe the bug
A screenshot or copy of the error could be helpful as well.

Make sure your bug can be reproduced with the Hazel Engine and not by your own engine that you're creating alongside with Hazel. For issues with your own engine, we're happy to help you in [TheCherno Discord server](https://thecherno.com/discord). Thanks for your understanding.

#### To Reproduce
4. See error above

#### Screenshots
If applicable, add extra screenshots to help explain your problem.

#### Operating system: (please complete the following information)
- OS: [e.g. win-64]
- Version: [e.g. Windows 10 home]

**Comment by VagueLobster** [comment]
I gotta say, veeeeerrrrryyyyy descriptive! Especially since it's in your own engine and not Hazel specifically 👍
