### ISSUE TITLE
Hello Everyone.

### ISSUE THREAD

**Issue by FlyingStudent** [TheCherno/Hazel#676]
Please consider using the Bug report or Feature request template. If it doesn't belong there, feel free to use this (empty) template. Make sure to provide enough details so it is clear for contributors to help you out. Premature or incomplete issues cannot be resolved due to lack of information or unclear descriptions.

Make sure your issue can be reproduced with the Hazel Engine and not by your own engine that you're creating alongside with Hazel. For issues with your own engine, we're happy to help you in [TheCherno Discord server](https://thecherno.com/discord). Thanks for your understanding.

**Comment by Kirdow** [comment]
Bro what are you doing. This is your second double post in the past month and both times you just post the same template unedited. GitHub Issues is meant for reporting issues with the project being worked on, not for trolling and causing shenanigans.
