### ISSUE TITLE
Really Need Help !

### ISSUE THREAD

**Issue by FlyingStudent** [TheCherno/Hazel#677]
Hello Everyone.
I know that this place is for issues related to Hazel but i really need help.
I have been following the game engine series with the great Yan Chernikov and once i have reached the new shader system i 've done everything but there is a slight problem which is the following :
GL_INVALID_ENUM on  glShaderBinary(1, &shaderID, GL_SHADER_BINARY_FORMAT_SPIR_V, spirv.data(), spirv.size() * sizeof(uint32_t))
I have tried several thigns like downloading anther vulkan sdk but it didn't work, i tried to pull the latest glad but it didn't work. 
I revised the code multiple times and didn't see a problem in it.
please someone help me because i need to continue with the series and finish it.
Thanks All ❤❤

![Screenshot (242)](https://github.com/TheCherno/Hazel/assets/138330536/89cc428c-58d7-4aa5-8432-79a433b400d6)

**Comment by Kirdow** [comment]
As written in the templates you've been using:
> Make sure your issue can be reproduced with the Hazel Engine and not by your own engine that you're creating alongside with Hazel. For issues with your own engine, we're happy to help you in [TheCherno Discord server](https://thecherno.com/discord). Thanks for your understanding.

This repository isn't for asking help with your own engine (as clearly stated in the template you're using), if you need help, join the discord server (as clearly linked in the template you're using).
