### ISSUE TITLE
ShaderBinary problem

### ISSUE THREAD

**Issue by FlyingStudent** [TheCherno/Hazel#678]
Hi Everyone,
First of all I want to apologize for misusing the Issues section in here.
But now, I came with a real thing that happened when i cloned Hazel.
I didn't clone it using the command line because there was a problem to me with that so i downloaded the zip archive and then unzipped it and downloaded all the necessary modules and downloaded and downloaded the vulkan sdk(1.3.211.0 version).
the problem this:
![Screenshot (244)](https://github.com/TheCherno/Hazel/assets/138330536/361d279a-1711-488c-90fb-4903e864d8d9)
Why is that happening ? What is the problem ?
(As the error message says: the error is in the glShaderBinary function and it is due to GL_SHADER_BINARY_FORMAT_SPIR_V,
But why it's an invalid enum since glad offers it and it's represented ? 
is there any other enum that would fit instead of GL_SHADER_BINARY_FORMAT_SPIR_V?)
Thanks all for helping ❤❤

**Comment by FlyingStudent** [comment]
It seems like the image isn't showing :
here is the image of my problem:
![Screenshot (244)](https://github.com/TheCherno/Hazel/assets/138330536/7049ddbb-67c6-46c7-8da3-92780530435f)

**Comment by VagueLobster** [comment]
It's probably happening because you're using an Intel integrated GPU and NOT a Nvidia or AMD dedicated GPU!!!
Intel GPU's and Vulkan are usually a no-go! + Hazel doesn't support Intel GPU's out of the box!

**Comment by VagueLobster** [comment]
> It's probably happening because you're using an Intel integrated GPU and NOT an Nvidia or AMD dedicated GPU!!! Intel GPU's and Vulkan are usually a no-go!

**Comment by FlyingStudent** [comment]
@VagueLobster 
You are right I am using an Intel GPU.
Is there anyway i can get vulkan to work on my Current GPU ? Or I need to upgrade ?

**Comment by VagueLobster** [comment]
> You are right I am using an Intel GPU. Is there anyway i can get vulkan to work on my Current GPU ? Or I need to upgrade ?

You would need to upgrade

**Comment by FlyingStudent** [comment]
@VagueLobster 
Thank you so much for your help ❤❤
