### ISSUE TITLE
Error in ./scripts/Setup.py

### ISSUE THREAD

**Issue by viktorpopp** [TheCherno/Hazel#682]
#### Describe the bug
I'm learning game engine dev and tried to take a look at Hazel. I clone the repository and all the submodules. I followed the Getting started section in the README.md. By the way I'm using Visual Studio 2022 Community. But when running Setup.py from Setup.bat there is an error in the file:
![image](https://github.com/TheCherno/Hazel/assets/162111707/3a46d905-d913-4c4d-99a8-6474d1d79bb0)

#### To Reproduce
1.  `git clone --recursive https://github.com/TheCherno/Hazel`
2. Run `Setup.bat` located in `./scripts`
3. Now the error should be seen.

#### Expected behavior
Generate project files for the engine.

#### Operating system: (please complete the following information)
- OS: win-64
- Version: Windows 11 home

**Comment by VidaTheHydroxZ** [comment]
Do you have git installed on your PC and added to the PATH on Windows? Also, in case you have git installed, did you use "git clone --recursive https://github.com/TheCherno/Hazel" command or you cloned the repository non-recursively and used "git submodule update --init" for the submodule updates?

If you clone the repository recursively with the first command you should be able to run "Setup.bat" not "Setup.py" and the script should do its job (installing all of the other things needed for the project).

**Comment by viktorpopp** [comment]
Thats exactly what i have done.

**Comment by VagueLobster** [comment]
> Thats exactly what i have done.

What version of python do you currently have installed?

**Comment by VagueLobster** [comment]
> Thats exactly what i have done.

You might have to update your python version to at least 3.12.3!
That's at least the version i'm using for my own engine with Hazel's code, and that works for me

**Comment by VagueLobster** [comment]
Plus you need to have both git + python in your PATH on windows, it's not enough with either one of them!
And the python 3.12.3 i'm using is the 64-bit version, i cannot say the 86x bit version will work with Hazel...
Lastly, if you have a pretty old version of git, you might want to consider updating it... it can't hurt to do so at least

**Comment by viktorpopp** [comment]
That does not help

**Comment by VagueLobster** [comment]
> That does not help

Hmm, then i only have one question... What type of GPU do you currently have? Is it Intel integrated GPU, is it an Nvidia or is it an AMD GPU, cause the latter does not work very well for everybody...

**Comment by viktorpopp** [comment]
Okay so i have reset my laptop (Ryzen 7 6800H, RTC 3070 Laptop) and now i found out that the problem was that git was added not added to path because that i was using Git Bash. Now i get a diffrent error. It says something like i have a problem with diffrent architectures. I cannot show a screenshot right now because i am out shopping but maybe in a 2-5 hours i can show a screenshot. (I am on my phone)

**Comment by viktorpopp** [comment]
So it is because that the vulkan installer is a 16-bit application.
![image](https://github.com/user-attachments/assets/493f6291-4c40-488d-a3df-c305ac29ab0a)

**Comment by Kirdow** [comment]
> So it is because that the vulkan installer is a 16-bit application.

Windows hasn't been 16-bit for about 40 years at this point. We're talking early to mid 80s during Windows 1.0 era. This sounds like an issue with your Windows installation if anything for it to treat executables made for 64-bit as if they're 16-bit. Especially considering Vulkan wasn't a thing until 2016 which is a time where even 32-bit started to become obsolete (which is even more the case nowadays).

I'm not sure what you can do to fix it other than formatting your drive, maybe someone else here have a better suggestion. Trying your steps though it runs fine for me.

**Comment by viktorpopp** [comment]
I found out that my Vulkan installation was corrupt and now it works. But it is still weird how Python/Windows said it was a 16-bit application. Thanks for the help :)

**Comment by yiluyujian** [comment]
> I found out that my Vulkan installation was corrupt and now it works. But it is still weird how Python/Windows said it was a 16-bit application. Thanks for the help :)

This is because the vulkanInstallURL in SetupVulkan.py is incorrect, which causes problems with the downloaded vulkanSDK.

**Comment by viktorpopp** [comment]
> 
> 
> 
> > I found out that my Vulkan installation was corrupt and now it works. But it is still weird how Python/Windows said it was a 16-bit application. Thanks for the help :)
> 
> This is because the vulkanInstallURL in SetupVulkan.py is incorrect, which causes problems with the downloaded vulkanSDK.

It was right back then.
