### ISSUE TITLE
Crash in OpenGLShader::Reflect

### ISSUE THREAD

**Issue by Mournx** [TheCherno/Hazel#688]
After I add SPIR_V System, when I run, a crash happened in OpenGLShader::Reflect
![QQ20241208-225329](https://github.com/user-attachments/assets/34a1e748-befb-4f79-9703-a1a6b31c7ad0)
and it only reflects the vertex shader.
Texture.glsl:14: error: '' :  syntax error, unexpected LAYOUT, expecting COMMA or SEMICOLON.
It seems like there is some problem in Texture.glsl.
![QQ20241208-225612](https://github.com/user-attachments/assets/3d6fd53f-dcec-4cf8-b014-f81e01c07380)
What's the matter? I really don't know.

**Comment by VagueLobster** [comment]
> After I add SPIR_V System, when I run, a crash happened in OpenGLShader::Reflect ![QQ20241208-225329](https://private-user-images.githubusercontent.com/114749264/393614681-34a1e748-befb-4f79-9703-a1a6b31c7ad0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2Nzk2OTAsIm5iZiI6MTczMzY3OTM5MCwicGF0aCI6Ii8xMTQ3NDkyNjQvMzkzNjE0NjgxLTM0YTFlNzQ4LWJlZmItNGY3OS05NzAzLWExYTZiMzFjN2FkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxNzM2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNmFmNTliMzUzNjUwZjJkNzMyYzI0ZTNmMWE0OWZhMDMyNmU4YTNiNDBlMTExY2I4M2JjMjgwZDJiNDRhN2Y5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.hYC9R8I9sCp-czhgGBdJVHkoLMEi5WYT1UIp42IPjuU) and it only reflects the vertex shader. Texture.glsl:14: error: '' : syntax error, unexpected LAYOUT, expecting COMMA or SEMICOLON. It seems like there is some problem in Texture.glsl. ![QQ20241208-225612](https://private-user-images.githubusercontent.com/114749264/393614909-3d6fd53f-dcec-4cf8-b014-f81e01c07380.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM2Nzk2OTAsIm5iZiI6MTczMzY3OTM5MCwicGF0aCI6Ii8xMTQ3NDkyNjQvMzkzNjE0OTA5LTNkNmZkNTNmLWRjZWMtNGNmOC1iMDE0LWY4MWUwMWMwNzM4MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOFQxNzM2MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MDEwYTNjNTU2OGVlYjk0YTAyOGZkMmNiYjJhZjMwMzA5M2EwNGEyNmY2NmIwZWI2MjNmNTYxNDdiOGNlYjBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vE7wrPCsSztToImMF_MduapFzhcE37JhbdDiXzwIObM) What's the matter? I really don't know.

you forgot a semicolon after the VertexOutput struct in the fragment part of the shader

**Comment by Mournx** [comment]
oh, my default! After I add it, the situation don't change, it still crashed ans only reflected vertex shader.Do you know where may be wrong ?

**Comment by Mournx** [comment]
oh, I solve it! I only cached vertex shader so it can't find fragment shader cache, After I delete them and recompile, It works!
Thank you very much!
