### ISSUE TITLE
Segmentation fault...

### ISSUE THREAD

**Issue by NiGhMa** [TheCherno/Hazel#70]
Hi, 

I try to make a version of Hazel on my own step by step watching the videos. And I do that on linux (thanks again @cubedtear).

Since I implemented ImGui I get a Segmentation fault each time I try to run the application. I can't figure out what I'm doing wrong.

Here's my repo : https://github.com/NiGhMa/Hazelicious

If you could help me, I'll appreciate a lot.

Edit:

I found that the line 219 in _imgui_impl_opengl3.cpp_ ( `glBindSampler(0, 0);` ) causes the problem!
[Screenshot from 2019-07-01 13-32-46](https://user-images.githubusercontent.com/59047/60455798-7bf60100-9c05-11e9-9148-9b6f10d2f743.png)

And here's my glxinfo output (version)
```
server glx version string: 1.4
client glx version string: 1.4
GLX version: 1.4
    Max core profile version: 4.5
    Max compat profile version: 3.0
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.1
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.8
OpenGL core profile shading language version string: 4.50
OpenGL version string: 3.0 Mesa 18.2.8
OpenGL shading language version string: 1.30
OpenGL ES profile version string: OpenGL ES 3.1 Mesa 18.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.10
```

Thanks

**Comment by gold604** [comment]
Hello, I think It's caused because your OpenGL version does not support `glBindSampler()` and thus gives a segmentation fault. Try defining `GL_SAMPLER_BINDING` to _false_.

For further assistance with your **own** repo, please do not create issues here, rather ask for help at Cherno's discord server. I'm sure there are people that will be willing to help you :) 

Have a nice day!

**Comment by Gaztin** [comment]
Thank you @gold604. I concur. Please ask in our Discord server for problem regarding your own repositories!

**Comment by NiGhMa** [comment]
> Hello, I think It's caused because your OpenGL version does not support `glBindSampler()` and thus gives a segmentation fault. Try defining `GL_SAMPLER_BINDING` to _false_.
> 
> For further assistance with your **own** repo, please do not create issues here, rather ask for help at Cherno's discord server. I'm sure there are people that will be willing to help you :)
> 
> Have a nice day!
> 
> Edit:
> @Gaztin I think you should close this because it is not related to this repo.

Thanks for your insights and sorry I forgot I could use Discord for this kinf of things.
