### ISSUE TITLE
There is no = operator defined

### ISSUE THREAD

**Issue by rikseth** [TheCherno/Hazel#73]
https://github.com/TheCherno/Hazel/blob/982dcdfc5afe2ce74cb8297ad4e3c8fad79fc831/Hazel/src/Platform/OpenGL/OpenGLBuffer.h#L17

There is no = operator defined in Buffer.h for the BufferLayout then how is it gonna work?

**Comment by 3x3y3z3t** [comment]
`m_Layout = layout` will automatically copy `layout`'s content to `m_Layout` using its default copy constructor, so there is no need to override the operator =.
Anyway, this kind of question is not actually an issue so I think there is no need to create a new issue, just discuss in video comment is okay.
