### ISSUE TITLE
Exeption thrown by glCreateVertexArrays

### ISSUE THREAD

**Issue by RustyGuard** [TheCherno/Hazel#78]
Exception thrown at 0x0000000000000000 in Sandbox.exe: 0xC0000005: Access violation executing location 0x0000000000000000.
At line: 31, at: OpenGLVertexArray.cpp.

This error throws on Debug and Release Windows runs.

**Comment by zerolith** [comment]
check if your Card supports OpenGL 4.5 (I think) this is the minimum for this command. Had to adapt to lower OpenGL version for my Mac adaptation.

**Comment by RustyGuard** [comment]
Yes, my card supports OpenGL 3.3. I need to change it.

**Comment by RustyGuard** [comment]
But I change glCreateBuffers to glGenBuffers and glCreateVertexArrays to glGenVertexArrays. And all works fine. What gives to us using of new commands?

**Comment by LovelySanta** [comment]
This error will be fixed in a future PR. Had this error earlier today as glfw is mismatched by openGL.
[These hints](https://github.com/LovelySanta/Hazel/commit/792ff772f3bb605c7c010f639bd63d9ed6fa05e0) will make sure that error won't be thrown in the future.
