### ISSUE TITLE
OpenGL deprecated on macOS

### ISSUE THREAD

**Issue by Root3287** [TheCherno/Hazel#8]
I know I am writing this a little ahead, but I think I've heard in one of @TheCherno videos that he was going to use OpenGL for the game engine. Along with OpenGL he wanted the engine to have cross platform support. As of MacOS 10.14 OpenGL has been deprecated. They have frozen the state of OpenGL for now. All I recommend is using the Vulkan API or some other alternatives. 

[MacOS What's New](https://developer.apple.com/macos/whats-new/#deprecationsandremovedapis)

**Edit 1:** Changed Link to what's new

**Comment by seanny** [comment]
Yes, Vulkan would be the more appropriate and modern option as its essentially the successor to OpenGL and can be run on MacOS using the MoltenVK library (which also had the added benefit of Metal rendering).

**Comment by lccatala** [comment]
But wasn't Vulkan too early in development and, as such, unstable?
Therefore it would overcomplicate the development cycle of the engine,
which is already quite ambitious

**Comment by IronicallySerious** [comment]
The reason why TheCherno was going for a renderer based on OpenGL is that he has a quite advanced OpenGL tutorial already on his channel and he wanted to refer to those OpenGL tutorials during the game engine series that he is doing right now.

It's a sad twist of fate that Apple announced the deprecation shortly after he announced the Game engine series

**Comment by Root3287** [comment]
Who knows ¯\_(ツ)_/¯... He could do a Vulkan Tutorial too (would be nice).
I'll still keep this up for people on OSX running <10.14

**Comment by TheCherno** [comment]
Officially we'll be using Metal on macOS, OpenGL will be fine for now until that happens.

**Comment by 1111mp** [comment]
> 正式来说，我们将在 macOS 上使用 Metal，OpenGL 暂时还可以，直到发生这种情况。

It's 2022.

**Comment by nisaldilshan** [comment]
It's 2023
