### ISSUE TITLE
Warnings from sub modules

### ISSUE THREAD

**Issue by Jack-Punter** [TheCherno/Hazel#84]
When Cloning this repository and building, there are still some build warnings to do with some compiler options added in one of the submodules premake file. These warnings where removed in the static linking video when Cherno made a load of changes to all of the premake files. I think that the fix for this is Cherno simply pushing the changes he made to his forks of the libraries that we are using so that clean forks/clones contain the changes made to those premake files.
The Warnings in question are:

> `3>------ Rebuild All started: Project: ImGui, Configuration: Release x64 ------
> 1>cl : Command line warning D9002 : ignoring unknown option '-std=c11'
> 1>cl : Command line warning D9002 : ignoring unknown option '-lgdi32'

**Comment by LovelySanta** [comment]
Cherno did not push those changes to github after the episode. He did push those together with the next vids all at once. This resulted in the hazel repo to be the static linking, without the submodules being updated.

We're working on making it linux compatible in #82. That PR is still a draft, as we're waiting on cherno to merge some other PR's into the submodules. He did merged one submodule yet, but not the other.

Kind regards
lovely_santa

**Comment by LovelySanta** [comment]
It just came to my attention that these buildoptions sneaky pulled into the glfw premake 5 file, even after TheCherno/glfw#6. I'll mark this as unresolved in #82.

**Comment by LovelySanta** [comment]
This was fixed in https://github.com/TheCherno/Hazel/commit/24fb3bbacc3661edb7ae4a5c9d946f948b9dcecd
