### ISSUE TITLE
LayerStack::PopLayer is incorrect

### ISSUE THREAD

**Issue by jdunlap** [TheCherno/Hazel#87]
In LayerStack::PopLayer, a comparison is made as

if (it != m_Layers.end())

this should, however, be:

if (it != m_Layers.begin() + m_LayerInsertIndex)

otherwise, if the function is passed an overlay layer, it will happily remove and shift the last non-overlay layer to be an overlay when it decrements m_LayerInsertIndex.

**Comment by LovelySanta** [comment]
You are correct!
https://github.com/TheCherno/Hazel/blob/3352191dbcd5e18754be70b18a5e6744692a77ca/Hazel/src/Hazel/LayerStack.cpp#L29-L38
`std::find` will return the last pointer in case it didn't find it; here this is indeed `m_Layers.begin() + m_LayerInsertIndex` instead of `m_Layer.end()`.

**Comment by CleverSource** [comment]
Someone should make a pull request to have this fixed.

**Comment by jdunlap** [comment]
The pull request has been created [here](https://github.com/TheCherno/Hazel/pull/93).
