### ISSUE TITLE
Build fails when building for the first time after creating project with Premake

### ISSUE THREAD

**Issue by Puddlestomper** [TheCherno/Hazel#9]
As seen at 29:10 in Cherno's Premake video. This can be fixed by moving the post-build step to the Sandbox project instead of putting it in the Hazel project since then all the directories will already have been generated.

**Comment by Ryngetsu** [comment]
I tried to do that on my own, but failed. How would you do?

**Comment by Puddlestomper** [comment]
In premake5.lua remove the postbuildcommand under the windows filter from the Hazel project (line 65-68 in this case) and after the defines under the windows filter in the Sandbox project (line 119 in this case) add:
```
postbuildcommands
{
	("{COPY} ../bin/" .. outputdir .. "/Hazel/Hazel.dll" .. " ../bin/" .. outputdir .. "/%{prj.name}")
}
```

**Comment by Ryngetsu** [comment]
It works perfectly !

**Comment by Dragon9815** [comment]
Another way to fix this issue, is to build all projects into the same directory. With this you just completely eliminate the need for a post build step in the first place.

**Comment by LovelySanta** [comment]
The other solution that @TheCherno mensioned in his video, is actualy checking if the folder already exist, and if not, it will create it. So on the postbuildcommand I first check for the folder. This works __every__ time.
```
postbuildcommands
{
	("IF NOT EXIST ../bin/" .. outputdir .. "/Sandbox mkdir ../bin/" .. outputdir .. "/Sandbox"),
	("{COPY} ../bin/" .. outputdir .. "/Hazel/Hazel.dll" .. " ../bin/" .. outputdir .. "/%{prj.name}")
}
```

**Comment by Husamdababneh** [comment]
Another solution is to just add a backslash to the end of the string to indicate that it's a directory but premake just removes that backslash so you'll have to surround the output path with quotations marks like this
```
postbuildcommands
{
	("{COPY} %{cfg.buildtarget.relpath} \"../bin/" .. outputdir .. "/Sandbox\\\"")
}
```
#22
