### ISSUE TITLE
Incorrect cases in GetComponentCount

### ISSUE THREAD

**Issue by Erwln** [TheCherno/Hazel#94]
The [OpenGL specification](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml) states that the `size` argument of the `glVertexAttribPointer`  function must be 1, 2, 3, or 4. However: https://github.com/TheCherno/Hazel/blob/3c147806f0b253e4a288b64e65a81948d63f112e/Hazel/src/Hazel/Renderer/Buffer.h#L46-L65

There are cases in which 9 or 16 may be returned, and this method is used to generate the `size` argument as described above in: https://github.com/TheCherno/Hazel/blob/3c147806f0b253e4a288b64e65a81948d63f112e/Hazel/src/Platform/OpenGL/OpenGLVertexArray.cpp#L61-L66

**Comment by WhoseTheNerd** [comment]
I don't see anything wrong, can you clarify what's wrong about that piece of code?

**Comment by LovelySanta** [comment]
As I'm reading this, these lines will return a component count of 9 and 12 respectivly, which, i think is correct?
https://github.com/TheCherno/Hazel/blob/3c147806f0b253e4a288b64e65a81948d63f112e/Hazel/src/Hazel/Renderer/Buffer.h#L54-L55

But as [the OpenGL specification](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glVertexAttribPointer.xhtml) says for the second parameter:
> `size`:
> Specifies the number of components per generic vertex attribute. Must be 1, 2, 3, 4. Additionally, the symbolic constant GL_BGRA is accepted by **glVertexAttribPointer**. The initial value is 4.

Meaning the return value of the `ShaderDataTypeToOpenGLBaseType` function (as shown above) will result in an error as it returns a value that is higher than 4? Which in that case would result in an error:
> `GL_INVALID_VALUE`:
> Generated if size is not 1, 2, 3, 4 or (for **glVertexAttribPointer**), GL_BGRA.

As I am not sure, my intuition says it correct, but the documentation clearly states it's not...

**Comment by Erwln** [comment]
Yes, that is the discrepancy I'm referring to. Small correction: it is `GetComponentCount()` that returns the `size`, not `ShaderDataTypeToOpenGLBaseType`.

**Comment by PhilipKatis** [comment]
I don't think we would ever even need to send a mat3 or mat4 as vertex buffer attribute.

**Comment by LovelySanta** [comment]
> Yes, that is the discrepancy I'm referring to. Small correction: it is `GetComponentCount()` that returns the `size`, not `ShaderDataTypeToOpenGLBaseType`.

Fixed my typo, thanks

> I don't think we would ever even need to send a mat3 or mat4 as vertex buffer attribute.

It's about correctness... If we wouldn't support it, then we wouldn't add it in the first place...

**Comment by rijenkii** [comment]
Also, bool can't be a vertex buffer attribute

**Comment by Puddlestomper** [comment]
I would like to point out [this information](https://www.khronos.org/opengl/wiki/Vertex_Specification#Matrix_attributes) from the OpenGL specification.

I would also like to point out that `Buffer.h` is part of our RendererAPI independent code and it might be standard in other APIs to provide the full size (I don't know other APIs so I can't say for sure). In that case this can stay as is and should be handled as a special case on the OpenGL side of the code.

Either way there should probably be specific code on the OpenGL side to handle the case for matrices properly.

**Comment by LovelySanta** [comment]
> I would like to point out [this information](https://www.khronos.org/opengl/wiki/Vertex_Specification#Matrix_attributes) from the OpenGL specification.
> 
> I would also like to point out that `Buffer.h` is part of our RendererAPI independent code and it might be standard in other APIs to provide the full size (I don't know other APIs so I can't say for sure). In that case this can stay as is and should be handled as a special case on the OpenGL side of the code.
> 
> Either way there should probably be specific code on the OpenGL side to handle the case for matrices properly.

Yes, the function itself is correct, but it is still an error that OpenGL is using this. So it is still a valid issue, we just need an OpenGL solution for this
