### ISSUE TITLE
ELEMENT_ARRAY_BUFFER can't be bound while current VBO is 0

### ISSUE THREAD

**Issue by rijenkii** [TheCherno/Hazel#95]
According to [Khronos Wiki](https://www.khronos.org/opengl/wiki/Vertex_Specification#Vertex_Array_Object),

>The core OpenGL profile makes VAO object 0 not an object at all. So if VAO 0 is bound in the core profile, you should not call any function that modifies VAO state. **This includes binding the `GL_ELEMENT_ARRAY_BUFFER` with glBindBuffer.**

`OpenGLIndexBuffer` constructor doesn't check that currently bound VAO is not 0.

**Comment by CleverSource** [comment]
You should make a PR which resolves this issue.

**Comment by rijenkii** [comment]
A reasonable fix would be changing the binding target in the constructor to something other than `GL_ELEMENT_BUFFER_OBJECT`, but to what? `GL_ARRAY_BUFFER`? `GL_COPY_WRITE_BUFFER`? And should we unbind it after a call to `glBufferData`?

**Comment by CleverSource** [comment]
Like I recommended; you should just make a pull request and if someone feels it needs improvement it will get reviewed (and if someone believe it's fine then it will get merged). I recommend you provide an example that can be tested showing how without your PR it doesn't work normally. 👍

**Comment by LovelySanta** [comment]
> A reasonable fix would be changing the binding target in the constructor to something other than `GL_ELEMENT_BUFFER_OBJECT`, but to what? `GL_ARRAY_BUFFER`? `GL_COPY_WRITE_BUFFER`?

It should be a generic data buffer, so `GL_ARRAY_BUFFER` is fine.

> And should we unbind it after a call to `glBufferData`?

Cherno mensioned this in his video, unbinding is not required, as it is just overhead. We support the unbind functions, but they shouldn't be needed. (only the VA needs unbinding)
